//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_10710(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10730(int32_t i_a1);
int32_t function_1073c(int32_t i_a1);
int32_t function_10748(int32_t i_a1, int32_t i_a2, int32_t *p_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6, int32_t *p_a7);
int32_t function_10754(void);
int32_t function_10760(int32_t i_a1);
int32_t function_1076c(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4);
int32_t function_10778(int32_t i_a1, int32_t *p_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6);
int32_t function_10784(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_10790(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_1079c(int32_t *p_a1, int32_t *p_a2, int32_t *p_a3,
                       int32_t *p_a4);
int32_t function_107a8(int32_t *p_a1);
int32_t function_107b4(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4);
int32_t function_107c0(int32_t i_a1, char *p_a2, int32_t i_a3, int32_t *p_a4);
int32_t function_107cc(int32_t i_a1, int32_t i_a2);
int32_t function_107d8(int32_t *p_a1, int32_t i_a2);
int32_t function_107e4(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_107f0(int32_t i_a1, int32_t i_a2);
int32_t function_107fc(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10808(void);
int32_t function_10818(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10824(int32_t i_a1);
int32_t function_10830(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4);
int32_t function_1083c(int32_t i_a1);
int32_t function_10848(int32_t *p_a1);
int32_t function_10854(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10860(int32_t i_a1, char *p_a2, int32_t i_a3);
int32_t function_108a0(void);
int32_t function_108c4(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_10914(void);
int32_t function_1092c(int32_t i_a1);
int32_t function_109e0(int32_t *p_a1);
int32_t function_10bd4(void);
int32_t function_10ca8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10e20(int32_t i_a1, uint32_t i_a2, int32_t i_a3, uint32_t i_a4,
                       uint32_t i_a5, uint32_t i_a6);
int32_t function_11498(int32_t i_a1);
int32_t function_114c8(int32_t i_a1);
int32_t function_11500(uint64_t i_a1, int32_t i_a2);
int32_t function_1154c(int64_t i_a1, int32_t i_a2, uint32_t i_a3);
int32_t function_115d0(int64_t i_a1, int32_t i_a2, int64_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6);
int32_t function_11700(int32_t i_a1, uint32_t i_a2);
int32_t function_11a24(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_11a3c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6, int32_t i_a7, int32_t i_a8,
                       int32_t i_a9);
int32_t function_11c08(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_11e00(uint32_t i_a1);
int32_t function_11f88(void);
int32_t function_11f90(int64_t i_a1, int64_t i_a2, int32_t i_a3);
int32_t function_11ff4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_12114(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_121b8(int32_t i_a1, uint32_t i_a2, int32_t i_a3);
int32_t function_12c6c(int32_t i_a1, int32_t i_a2);
int32_t function_12c80(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_137e0(uint32_t i_a1, int32_t i_a2);
int32_t function_13bc4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_13c00(void);
int32_t function_13c04(int32_t i_a1, int32_t i_a2);
int32_t function_13c08(void);
int32_t function_13c10(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_e0832002(void);
int32_t function_e1a00003(void);
int32_t function_e1a02003(void);
int32_t function_e1a03000(void);
int32_t function_e1a0c003(void);
int32_t function_e1a0e002(void);
int32_t function_e2433004(void);
int32_t function_e243300c(void);
int32_t function_e24b3e51(void);
int32_t function_e3033fa8(void);
int32_t function_e3033fbc(void);
int32_t function_e3403001(void);
int32_t function_e58e0000(void);
int32_t function_e58e1004(void);
int32_t function_e58e2008(void);
int32_t function_e58e300c(void);
int32_t function_e5ce3010(void);
int32_t function_e5dc3000(void);
int32_t function_e8bc000f(void);
int32_t function_ea000064(void);
int32_t function_ebfffdce(void);
int32_t function_ff86c500(void);
int32_t function_ff86c880(void);
int32_t function_ff86cea8(void);
int32_t unknown_240(void);
int32_t unknown_412068(void);
int32_t unknown_4132b0(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x1092d; // 0x24f08
int32_t i_g2 = 0;       // 0x25074
int32_t i_g3 = 256;     // 0x25080
char *p_g4;             // 0x2583c
uint32_t i_g5;
int32_t i_g6;

// ------------------------ Functions -------------------------

// Address range: 0x10710 - 0x1071c
int32_t function_10710(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10710
    return function_108a0();
}

// Address range: 0x10730 - 0x1073c
int32_t function_10730(int32_t i_a1) {
    // 0x10730
    return function_e243300c();
}

// Address range: 0x1073c - 0x10748
int32_t function_1073c(int32_t i_a1) {
    // 0x1073c
    return function_e0832002();
}

// Address range: 0x10748 - 0x10754
int32_t function_10748(int32_t i_a1, int32_t i_a2, int32_t *p_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6, int32_t *p_a7) {
    // 0x10748
    return function_e3033fa8();
}

// Address range: 0x10754 - 0x10760
int32_t function_10754(void) {
    // 0x10754
    return function_e3403001();
}

// Address range: 0x10760 - 0x1076c
int32_t function_10760(int32_t i_a1) {
    // 0x10760
    return function_e1a0e002();
}

// Address range: 0x1076c - 0x10778
int32_t function_1076c(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4) {
    // 0x1076c
    return function_e1a0c003();
}

// Address range: 0x10778 - 0x10784
int32_t function_10778(int32_t i_a1, int32_t *p_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6) {
    // 0x10778
    return function_e8bc000f();
}

// Address range: 0x10784 - 0x10790
int32_t function_10784(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x10784
    return function_e58e0000();
}

// Address range: 0x10790 - 0x1079c
int32_t function_10790(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10790
    return function_e58e1004();
}

// Address range: 0x1079c - 0x107a8
int32_t function_1079c(int32_t *p_a1, int32_t *p_a2, int32_t *p_a3,
                       int32_t *p_a4) {
    // 0x1079c
    return function_e58e2008();
}

// Address range: 0x107a8 - 0x107b4
int32_t function_107a8(int32_t *p_a1) {
    // 0x107a8
    return function_e58e300c();
}

// Address range: 0x107b4 - 0x107c0
int32_t function_107b4(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4) {
    // 0x107b4
    return function_e5dc3000();
}

// Address range: 0x107c0 - 0x107cc
int32_t function_107c0(int32_t i_a1, char *p_a2, int32_t i_a3, int32_t *p_a4) {
    // 0x107c0
    return function_e5ce3010();
}

// Address range: 0x107cc - 0x107d8
int32_t function_107cc(int32_t i_a1, int32_t i_a2) {
    // 0x107cc
    return function_ea000064();
}

// Address range: 0x107d8 - 0x107e4
int32_t function_107d8(int32_t *p_a1, int32_t i_a2) {
    // 0x107d8
    return function_e24b3e51();
}

// Address range: 0x107e4 - 0x107f0
int32_t function_107e4(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x107e4
    return function_e2433004();
}

// Address range: 0x107f0 - 0x107fc
int32_t function_107f0(int32_t i_a1, int32_t i_a2) {
    // 0x107f0
    return function_e243300c();
}

// Address range: 0x107fc - 0x10808
int32_t function_107fc(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t i_a4) {
    // 0x107fc
    return function_e1a00003();
}

// Address range: 0x10808 - 0x10818
int32_t function_10808(void) {
    // 0x10808
    return function_ebfffdce();
}

// Address range: 0x10818 - 0x10824
int32_t function_10818(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10818
    return function_e1a03000();
}

// Address range: 0x10824 - 0x10830
int32_t function_10824(int32_t i_a1) {
    // 0x10824
    return function_e1a02003();
}

// Address range: 0x10830 - 0x1083c
int32_t function_10830(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4) {
    // 0x10830
    return function_e24b3e51();
}

// Address range: 0x1083c - 0x10848
int32_t function_1083c(int32_t i_a1) {
    // 0x1083c
    return function_e2433004();
}

// Address range: 0x10848 - 0x10854
int32_t function_10848(int32_t *p_a1) {
    // 0x10848
    return function_e243300c();
}

// Address range: 0x10854 - 0x10860
int32_t function_10854(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t i_a4) {
    // 0x10854
    return function_e0832002();
}

// Address range: 0x10860 - 0x1086c
int32_t function_10860(int32_t i_a1, char *p_a2, int32_t i_a3) {
    // 0x10860
    return function_e3033fbc();
}

// Address range: 0x10870 - 0x10898
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10870
    int32_t i_v1; // 0x10870
    int32_t i_v2 = function_10748(0x137e0, i_a2, &i_v1, 0x13bc5, 0x137e0, i_a1,
                                  &i_v1); // 0x1088c
    return function_10730(i_v2);
}

// Address range: 0x108a0 - 0x108bc
int32_t function_108a0(void) {
    // 0x108a0
    if (i_g2 == 0) {
        int32_t i_v1; // 0x108a0
        return i_v1;
    }
    // 0x108b8
    return function_10754();
}

// Address range: 0x108c4 - 0x10914
int32_t function_108c4(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x108c4
    int32_t i_v1; // 0x108c4
    int32_t i_v2 = i_v1;
    bool i_v3; // 0x108c4
    if (i_v3) {
        return i_a1;
    }
    bool i_v4; // 0x108c4
    if (!i_v3) {
        int32_t i_v5 = 0x100001 * i_v2 & -1 - 0x400000 * i_v2; // 0x108fc
        i_v4 = i_v5 < 0;
        if (i_v5 == 0) {
            return unknown_240();
        }
    }
    // 0x1090c
    if (i_v4 != i_v3) {
        __asm_svclt(0x4770);
    }
    return i_a1;
}

// Address range: 0x10914 - 0x1092c
int32_t function_10914(void) {
    // 0x10914
    int32_t i_v1; // 0x10914
    if (*(char *)&p_g4 == 0) {
        // 0x10922
        int32_t i_v2;                                       // 0x10914
        int32_t i_v3 = function_108c4(i_v2, i_v2, i_v2, 0); // 0x10922
        *(char *)&p_g4 = 1;
        i_v1 = i_v3;
    }
    // 0x1092a
    return i_v1;
}

// Address range: 0x1092c - 0x109e0
int32_t function_1092c(int32_t i_a1) {
    int32_t i_v1; // 0x1092c
    function_10818("Useage:\r", i_v1, i_v1, i_v1);
    function_107e4("\t%s [option] [paramaters]\n\n", i_a1, i_v1, i_v1);
    function_10818("\tOption:{-f} {-s} {-p} {-n} {-x} {-q}\n", i_a1, i_v1,
                   i_v1);
    function_10818("\t\t-f [minerType] [fileName] [rootPublicKeyFile]: "
                   "\n\t\t\tOnly Check If Filename was Valided.\n",
                   i_a1, i_v1, i_v1);
    function_10818(
        "\t\t-s [minerType] [fileName] [rootPublicKeyFile]: \n\t\t\tCheck If "
        "Filename Was Valided, and Splite Bmu To \"/tmp/tmpfw/\"\n",
        i_a1, i_v1, i_v1);
    function_10818(
        "\t\t-p [minerType] [fileName] [rootPublicKeyFile]: \n\t\t\tCheck If "
        "Filename Was Valided, and Dump BmuComments\n",
        i_a1, i_v1, i_v1);
    function_10818("\t\t-x [minerType] [fileName] [rootPublicKeyFile]: "
                   "\n\t\t\tCheck If Filename Was FullSize BMU\n",
                   i_a1, i_v1, i_v1);
    function_10818("\t\t-n [nandBinFile]: \n\t\t\tSplite SigImg To Single File "
                   "To \"/tmp/tmpNand/\"\n",
                   i_a1, i_v1, i_v1);
    function_10818(
        "\t\t-q: \n\t\t\tGenerate A 256Bytes 0xff File To \"/tmp/256BFF\"\n",
        i_a1, i_v1, i_v1);
    function_10818("\tReturns:", i_a1, i_v1, i_v1);
    function_10818("\t\t0: \n\t\t\tWell Done!\n", i_a1, i_v1, i_v1);
    return __asm_nop(function_10818("\t\tOthers: \n\t\t\tSomething Wrong!\n",
                                    i_a1, i_v1, i_v1));
}

// Address range: 0x109e0 - 0x10bd4
int32_t function_109e0(int32_t *p_a1) {
    int32_t i_v1 = 0; // bp-32788, 0x10a08
    int32_t i_v2;     // bp-32784, 0x109e0
    function_1076c(&i_v2, 0, 0x7ffc, &i_v2);
    int32_t i_v3; // bp-32776, 0x109e0
    int32_t i_v4 =
        function_107c0((int32_t)p_a1, "rb", 0x7ffc, &i_v3); // 0x10a34
    int32_t i_v5 = 0;                                       // 0x10a44
    if (i_v4 == 0) {
        // 0x10a48
        function_10818("Load Nand Image File Failed!", (int32_t) "rb", 0x7ffc,
                       0);
        // 0x10bc8
        return 1;
    }
    int32_t i_v6 = 132 * i_v5;                          // 0x10a88
    int32_t *p_v7 = (int32_t *)(i_v6 + (int32_t)&i_g3); // 0x10a90
    function_10854(&i_v1, *p_v7, 1, i_v4);
    int32_t i_v8 = i_v6 + (int32_t)&i_g3 + 4; // 0x10acc
    int32_t i_v9 =
        function_107c0(i_v8, "wb", (int32_t)&i_g3, (int32_t *)i_v8); // 0x10adc
    int32_t i_v10;                                                   // 0x109e0
    while (i_v9 != 0) {
        // 0x10b40
        function_107fc(&i_v1, *p_v7, 1, i_v9);
        function_10760(i_v9);
        i_v5++;
        if (i_v5 >= 15) {
            // 0x10bbc
            function_10760(i_v4);
            i_v10 = 0;
            return i_v10;
        }
        i_v6 = 132 * i_v5;
        p_v7 = (int32_t *)(i_v6 + (int32_t)&i_g3);
        function_10854(&i_v1, *p_v7, 1, i_v4);
        i_v8 = i_v6 + (int32_t)&i_g3 + 4;
        i_v9 = function_107c0(i_v8, "wb", (int32_t)&i_g3, (int32_t *)i_v8);
    }
    // 0x10b30
    function_107e4("Try To Write To File '%s' Failed!\n", i_v8, (int32_t)&i_g3,
                   i_v8);
    function_10760(i_v4);
    i_v10 = 2;
lab_0x10bc8:
    // 0x10bc8
    return i_v10;
}

// Address range: 0x10bd4 - 0x10ca8
int32_t function_10bd4(void) {
    // 0x10bd4
    int32_t i_v1; // 0x10bd4
    int32_t i_v2 = function_107c0((int32_t) "/tmp/256BFF", "wb", i_v1,
                                  (int32_t *)i_v1); // 0x10bf0
    if (i_v2 == 0) {
        // 0x10c04
        function_10818("GenFile Failed!", (int32_t) "wb", i_v1, 0);
        // 0x10c9c
        return 1;
    }
    int32_t i_v3 = 0; // bp-272, 0x10c1c
    int32_t i_v4;     // bp-268, 0x10bd4
    function_1076c(&i_v4, 0, 252, &i_v4);
    for (int32_t i_v5 = 0; i_v5 < 256; i_v5++) {
        // 0x10c48
        *(char *)(i_v5 + (int32_t)&i_v3) = -1;
    }
    // 0x10c74
    function_107fc(&i_v3, 256, 1, i_v2);
    function_10760(i_v2);
    // 0x10c9c
    return 0;
}

// Address range: 0x10ca8 - 0x10e20
int32_t function_10ca8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_107cc(i_a4, 1024);    // 0x10cdc
    int32_t i_v2 = function_10790(i_v1, 0, 0, 0); // 0x10cf4
    if (i_v2 == 0) {
        int32_t i_v3 = function_107f0(function_1073c(0), 0); // 0x10d18
        function_107e4("OpenSSL error: %s\n", i_v3, 0, i_v3);
        function_10818("Read Root PubK Failed!", i_v3, 0, i_v3);
        // 0x10e14
        return 12;
    }
    // 0x10d44
    int32_t i_v4; // bp-164, 0x10ca8
    function_10848(&i_v4);
    function_10830(&i_v4, i_a1, i_a2, &i_v4);
    int32_t i_v5; // bp-52, 0x10ca8
    function_1079c(&i_v5, &i_v4, &i_v4, &i_v5);
    int32_t i_v6 = function_10778(672, &i_v5, 32, i_a3, 256, i_v2); // 0x10d98
    int32_t i_v7 = function_10824(i_v2);                            // 0x10dbc
    if (i_v1 != 0) {
        // 0x10dc0
        i_v7 = function_1083c(i_v1);
    }
    int32_t i_v8 = 0; // 0x10dd0
    if (i_v6 != 1) {
        int32_t i_v9 = function_107f0(function_1073c(i_v7), 0); // 0x10dec
        function_107e4("OpenSSL error: %s\n", i_v9, 32, i_v9);
        function_10818("Check miner.pem Failed!", i_v9, 32, i_v9);
        i_v8 = 13;
    }
    // 0x10e14
    return i_v8;
}

// Address range: 0x10e20 - 0x11498
int32_t function_10e20(int32_t i_a1, uint32_t i_a2, int32_t i_a3, uint32_t i_a4,
                       uint32_t i_a5, uint32_t i_a6) {
    int32_t i_v1 = 0; // bp-1044, 0x10e40
    int32_t i_v2;     // bp-1040, 0x10e20
    function_1076c(&i_v2, 0, 1020, &i_v2);
    int32_t i_v3; // bp-1156, 0x10e20
    function_10848(&i_v3);
    int32_t i_v4 = 0; // 0x10e94
    if (i_a6 % 256 != 0) {
        char *p_v5 = (char *)0x706d742f; // bp-1316, 0x10eb0
        int32_t i_v6;                    // bp-1304, 0x10e20
        function_1076c(&i_v6, 0, 116, &i_v6);
        i_g5 = i_a4 % 256;
        switch ((char)i_a4) {
        case 0: {
            int32_t i_v7 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x10f2c
            *(int32_t *)i_v7 = 0x544f4f42;
            *(int32_t *)(i_v7 + 4) = 0x6e69622e;
            *(char *)(i_v7 + 8) = 0;
            // break -> 0x111ec
            break;
        }
        case 1: {
            int32_t i_v8 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x10f78
            *(int32_t *)i_v8 = 0x69766564;
            *(int32_t *)(i_v8 + 4) = 0x72746563;
            *(int32_t *)(i_v8 + 8) = 0x642e6565;
            *(int16_t *)(i_v8 + 12) = 0x6274;
            *(char *)(i_v8 + 14) = 0;
            // break -> 0x111ec
            break;
        }
        case 2: {
            int32_t i_v9 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x10fd4
            *(int32_t *)i_v9 = 0x616d4975;
            *(int16_t *)(i_v9 + 4) = 0x6567;
            *(char *)(i_v9 + 6) = 0;
            // break -> 0x111ec
            break;
        }
        case 3: {
            int32_t i_v10 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x11024
            *(int32_t *)i_v10 = 0x656e696d;
            *(int32_t *)(i_v10 + 4) = 0x2e736672;
            *(int32_t *)(i_v10 + 8) = 0x67616d69;
            *(int32_t *)(i_v10 + 12) = 0x7a672e65;
            *(char *)(i_v10 + 16) = 0;
            // break -> 0x111ec
            break;
        }
        case 4: {
            int32_t i_v11 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x11080
            *(int32_t *)i_v11 = 0x61647075;
            *(int32_t *)(i_v11 + 4) = 0x692e6574;
            *(int32_t *)(i_v11 + 8) = 0x6567616d;
            *(int32_t *)(i_v11 + 12) = 0x7a672e;
            // break -> 0x111ec
            break;
        }
        case 5: {
            int32_t i_v12 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x110d4
            *(int32_t *)i_v12 = 0x2e6c7263;
            *(int32_t *)(i_v12 + 4) = 0x2e726174;
            *(int16_t *)(i_v12 + 8) = 0x7a67;
            *(char *)(i_v12 + 10) = 0;
            // break -> 0x111ec
            break;
        }
        case 6: {
            int32_t i_v13 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x11128
            *(int32_t *)i_v13 = 0x656e696d;
            *(int32_t *)(i_v13 + 4) = 0x74622e72;
            *(int32_t *)(i_v13 + 8) = 0x61742e6d;
            *(int32_t *)(i_v13 + 12) = 0x7a672e72;
            *(char *)(i_v13 + 16) = 0;
            // break -> 0x111ec
            break;
        }
        case 7: {
            int32_t i_v14 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x11184
            *(int32_t *)i_v14 = 0x65736572;
            *(int32_t *)(i_v14 + 4) = 0x657672;
            // break -> 0x111ec
            break;
        }
        case 9: {
            int32_t i_v15 =
                function_107a8((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x111c8
            *(int32_t *)i_v15 = 0x61746164;
            *(int32_t *)(i_v15 + 4) = 0x656c6966;
            *(char *)(i_v15 + 8) = 0;
            __asm_nop(0x61746164);
            // break -> 0x111ec
            break;
        }
        }
        int32_t i_v16; // 0x10e20
        if (i_a5 % 256 == 0) {
            // 0x111ec
            i_v16 = (int32_t)&p_v5;
        } else {
            int32_t i_v17 = function_107a8((int32_t *)&p_v5); // 0x11208
            int32_t i_v18 = (int32_t)&p_v5;
            int32_t i_v19 = i_v17 + i_v18; // 0x11220
            *(int32_t *)i_v19 = 0x6769732e;
            *(char *)(i_v19 + 4) = 0;
            i_v16 = i_v18;
        }
        int32_t i_v20 = i_v16;
        function_107e4("fileName:'%s', size:[%d]\r\n", i_v20, i_a2, i_v20);
        int32_t i_v21 =
            function_107c0(i_v20, "wb", i_a2, (int32_t *)&p_v5); // 0x11274
        i_v4 = i_v21;
        if (i_v21 == 0) {
            // 0x11288
            function_107e4("Create File '%s' Failed!\r\n", i_v20, i_a2, i_v20);
            i_v4 = 0;
        }
    }
    int32_t i_v22 = &i_v1;
    int32_t i_v23 = i_a2; // 0x11344
    if (i_a2 >= 1024 == (i_a2 != 1024)) {
        int32_t i_v24 = 0;                                    // 0x112d4
        int32_t i_v25 = function_10854(&i_v1, 1, 1024, i_a1); // 0x112c0
        function_10830(&i_v3, i_v22, 1024, &i_v3);
        if (i_a6 % 256 != 0 && i_v4 != 0) {
            // 0x11318
            function_107fc(&i_v1, 1, 1024, i_v4);
        }
        // 0x11334
        i_v24 += i_v25;
        int32_t i_v26 = i_a2 - i_v24; // 0x1133c
        i_v23 = i_v26;
        while (i_v26 >= 1024 == (i_v26 != 1024)) {
            // 0x112a8
            i_v25 = function_10854(&i_v1, 1, 1024, i_a1);
            function_10830(&i_v3, i_v22, 1024, &i_v3);
            if (i_a6 % 256 != 0 && i_v4 != 0) {
                // 0x11318
                function_107fc(&i_v1, 1, 1024, i_v4);
            }
            // 0x11334
            i_v24 += i_v25;
            i_v26 = i_a2 - i_v24;
            i_v23 = i_v26;
        }
    }
    int32_t i_v27 = function_10854(&i_v1, 1, i_v23, i_a1); // 0x11368
    function_10830(&i_v3, i_v22, i_v27, &i_v3);
    int32_t i_v28; // bp-1188, 0x10e20
    if (i_a6 % 256 == 0 || i_v4 == 0) {
        // 0x113cc
        i_v28 = 0;
        function_1079c(&i_v28, &i_v3, &i_v3, &i_v28);
    } else {
        // 0x1143c
        function_107fc(&i_v1, 1, i_v27, i_v4);
        i_v28 = 0;
        function_1079c(&i_v28, &i_v3, &i_v3, &i_v28);
        function_10760(i_v4);
    }
    // 0x1144c
    *(int32_t *)i_a3 = i_v28;
    *(int32_t *)(i_a3 + 4) = 0;
    *(int32_t *)(i_a3 + 8) = 0;
    *(int32_t *)(i_a3 + 12) = 0;
    *(int32_t *)(i_a3 + 16) = 0;
    *(int32_t *)(i_a3 + 20) = 0;
    *(int32_t *)(i_a3 + 24) = 0;
    *(int32_t *)(i_a3 + 28) = 0;
    __asm_nop(0);
    return 0;
}

// Address range: 0x11498 - 0x114c8
int32_t function_11498(int32_t i_a1) {
    // 0x11498
    return i_a1;
}

// Address range: 0x114c8 - 0x11500
int32_t function_114c8(int32_t i_a1) {
    // 0x114c8
    int64_t i_v1; // bp-16, 0x114c8
    function_107b4((int32_t *)&i_v1, i_a1, 8, (int32_t *)&i_v1);
    return (0x100000000 * i_v1 >> 32) / 0x100000000;
}

// Address range: 0x11500 - 0x1154c
int32_t function_11500(uint64_t i_a1, int32_t i_a2) {
    // 0x11500
    return ((int64_t)(0x100000000 * i_a1) >> 32) / 0x100000000 ^
           i_a1 / 0x8000 % 0x20000;
}

// Address range: 0x1154c - 0x115d0
int32_t function_1154c(int64_t i_a1, int32_t i_a2, uint32_t i_a3) {
    uint64_t i_v1 = 0x100000000 * i_a1 >> 32;      // 0x11560
    uint32_t i_v2 = (int32_t)i_v1;                 // 0x11560
    uint32_t i_v3 = (int32_t)(i_v1 / 0x100000000); // 0x11560
    return i_v2 >> i_a3 - 32 | i_v2 << 32 - i_a3 | i_v3 >> i_a3 |
           i_v3 << -i_a3 % 64;
}

// Address range: 0x115d0 - 0x11700
int32_t function_115d0(int64_t i_a1, int32_t i_a2, int64_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6) {
    int32_t i_v1 = i_a3;
    int32_t i_v2 =
        ((i_v1 >> 31 ^ (int32_t)((0x100000000 * i_a1 >> 32) / 0x100000000)) *
             i_a5 ^
         i_v1) /
        0x80000000 * i_a5; // 0x11678
    return (i_v2 >> 31 ^ i_v2 / 0x8000) * i_a5 / 0x80000000;
}

// Address range: 0x11700 - 0x11a24
int32_t function_11700(int32_t i_a1, uint32_t i_a2) {
    // 0x11700
    if (i_a2 != 7 && i_a2 >= 7) {
        int32_t i_v1 = (2 * i_a2 - 0x651e95c5) / 0x80000000;
        int32_t i_v2 = function_114c8(i_a1) - 0x651e95c5 >> 31;
        int32_t i_v3 = function_114c8(i_a2 + i_a1 - 8); // 0x1178c
        int32_t i_v4 = i_v3 >> 31;
        int32_t i_v5 =
            function_1154c((int64_t)i_v4, i_v3, 37) * i_v1 + i_v2 >> 31;
        int32_t i_v6 =
            (function_1154c((int64_t)i_v2, i_v2, 25) + i_v4) * i_v1; // 0x11818
        // 0x11a14
        return function_115d0((int64_t)i_v5, i_v5, (int64_t)(i_v6 >> 31), i_v6,
                              i_v1, i_v1);
    }
    if (i_a2 != 3 && i_a2 >= 3) {
        int32_t i_v7 = 2 * i_a2 - 0x651e95c5;           // 0x11870
        int32_t i_v8 = 8 * function_11498(i_a1) + i_a2; // 0x118b0
        // 0x11a14
        return function_115d0((int64_t)(i_v8 >> 31), i_v8,
                              (int64_t)function_11498(i_a2 + i_a1 - 4), 0,
                              i_v7 >> 31, i_v7);
    }
    int32_t i_v9 = -0x651e95c5; // 0x11910
    if (i_a2 != 0) {
        unsigned char i_v10 = *(char *)(i_a2 / 2 + i_a1); // 0x11930
        unsigned char i_v11 = *(char *)(i_a2 + i_a1 - 1); // 0x11948
        int32_t i_v12;                                    // 0x11700
        int32_t i_v13 = -0x3c5a37a4 * (4 * (int32_t)i_v11 + i_a2) ^
                        -0x651e95c5 * (256 * (int32_t)i_v10 |
                                       (uint32_t)i_v12 % 256); // 0x119d0
        i_v9 = -0x651e95c5 * function_11500((int64_t)(i_v13 >> 31), i_v13);
    }
    // 0x11a14
    return i_v9;
}

// Address range: 0x11a24 - 0x11a3a
int32_t function_11a24(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    int32_t i_v1 = unknown_412068();       // 0x11a24
    int32_t i_v2 = *(int32_t *)(i_v1 + 4); // 0x11a34
    int32_t i_v3 = i_v1 + 16;              // 0x11a34
    *(int32_t *)i_v2 = i_v3;
    *(int32_t *)(i_v2 + 4) = *(int32_t *)i_v1;
    int32_t i_v4; // 0x11a24
    *(int32_t *)(i_v2 + 12) = i_v4 ^ i_a2;
    return i_v3;
}

// Address range: 0x11a3c - 0x11c08
int32_t function_11a3c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6, int32_t i_a7, int32_t i_a8,
                       int32_t i_a9) {
    int32_t i_v1 = 2 * i_a2 - 0x651e95c5;    // 0x11a64
    int32_t i_v2 = function_114c8(i_a1);     // 0x11a74
    int32_t i_v3 = function_114c8(i_a1 + 8); // 0x11aac
    int32_t i_v4 = i_a2 + i_a1;
    int32_t i_v5 = function_114c8(i_v4 - 8) * i_v1; // 0x11ae4
    int32_t i_v6 = function_114c8(i_v4 - 16);       // 0x11b0c
    int32_t i_v7 = -0x4b6d4991 * i_v2 >> 31;
    int32_t i_v8 = i_v3 >> 31;
    int32_t i_v9 = i_v7 + i_v8;                                      // 0x11b40
    int32_t i_v10 = function_1154c((int64_t)(i_v9 >> 31), i_v9, 43); // 0x11b58
    int32_t i_v11 = i_v5 >> 31;
    int32_t i_v12 = function_1154c((int64_t)i_v11, i_v5, 30) + i_v10 +
                    (-0x651e95c5 * i_v6 >> 31); // 0x11b84
    int32_t i_v13 = i_v8 - 0x651e95c5;          // 0x11ba0
    int32_t i_v14 =
        i_v11 + i_v7 +
        function_1154c((int64_t)(i_v13 >> 31), i_v13, 18); // 0x11bcc
    return function_115d0((int64_t)(i_v12 >> 31), i_v12, (int64_t)(i_v14 >> 31),
                          i_v14, i_v1 >> 31, i_v1);
}

// Address range: 0x11c08 - 0x11dfc
int32_t function_11c08(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x11c08
    int32_t i_v1; // 0x11c08
    bool i_v2;    // 0x11c08
    if (i_v2) {
        __asm_svchs(0x90404f);
        i_v1 = i_a1;
        if (i_v2) {
            // .thread
            i_v1 = function_ff86c500();
            goto lab_0x11c10;
        } else {
            goto lab_0x11c10;
        }
    } else {
        // .thread
        i_v1 = function_ff86c500();
        goto lab_0x11c10;
    }
lab_0x11c10:;
    int32_t i_v3 = 2 * i_a2 - 0x651e95c5;    // 0x11c44
    int32_t i_v4 = function_114c8(i_v1);     // 0x11c54
    int32_t i_v5 = function_114c8(i_v1 + 8); // 0x11c8c
    int32_t i_v6 = i_v1 + i_a2;
    int32_t i_v7 = function_114c8(i_v6 - 8) * i_v3; // 0x11cc4
    int32_t i_v8 = function_114c8(i_v6 - 16);       // 0x11cec
    int32_t i_v9 = -0x651e95c5 * i_v4 >> 31;
    int32_t i_v10 = i_v5 >> 31;
    int32_t i_v11 = i_v9 + i_v10; // 0x11d20
    int32_t i_v12 =
        function_1154c((int64_t)(i_v11 >> 31), i_v11, 43); // 0x11d38
    int32_t i_v13 = i_v7 >> 31;
    int32_t i_v14 = (function_1154c((int64_t)i_v13, i_v7, 30) + i_v12 +
                     (-0x651e95c5 * i_v8 >> 31)) /
                    0x80000000;
    int32_t i_v15 = i_v10 - 0x651e95c5; // 0x11d88
    int32_t i_v16 =
        i_v13 + i_v9 +
        function_1154c((int64_t)(i_v15 >> 31), i_v15, 18); // 0x11db4
    function_115d0((int64_t)i_v14, i_v14, (int64_t)(i_v16 >> 31), i_v16,
                   i_v3 >> 31, i_v3);
    return function_114c8(i_v1 + 16);
}

// Address range: 0x11e00 - 0x11f88
int32_t function_11e00(uint32_t i_a1) {
    // 0x11e00
    int32_t i_v1;                                        // 0x11e00
    int32_t *p_v2 = (int32_t *)(i_v1 - 36);              // 0x11e00
    uint64_t i_v3 = (int64_t)*p_v2 * (int64_t)i_a1;      // 0x11e04
    int32_t i_v4 = i_v1 + (int32_t)(i_v3 / 0x100000000); // 0x11e08
    int32_t i_v5 = i_v1 - 92;                            // 0x11e10
    *(int32_t *)i_v5 = (int32_t)i_v3;
    *(int32_t *)(i_v1 - 88) = i_v4;
    int32_t *p_v6 = (int32_t *)(i_v1 - 120);   // 0x11e18
    int32_t i_v7 = function_114c8(*p_v6 + 24); // 0x11e24
    int32_t i_v8 = i_v1 - 100;                 // 0x11e28
    *(int32_t *)i_v8 = i_v7;
    *(int32_t *)(i_v1 - 96) = i_v4;
    int32_t *p_v9 = (int32_t *)(i_v1 - 124);                 // 0x11e2c
    uint32_t i_v10 = function_114c8(*p_v9 - 32 + *p_v6);     // 0x11e40
    uint64_t i_v11 = *(int64_t *)(i_v1 - 76);                // 0x11e44
    uint32_t i_v12 = i_v10 + (int32_t)(i_v11 / 0x100000000); // 0x11e48
    int32_t i_v13 = i_v1 - 156;                              // 0x11e4c
    *(int32_t *)i_v13 = i_v12;
    *(int32_t *)(i_v1 - 152) = i_v4 + (int32_t)i_v11 + (int32_t)(i_v12 < i_v10);
    int32_t *p_v14 = (int32_t *)(i_v1 - 32); // 0x11e58
    int32_t i_v15 = *p_v14;                  // 0x11e58
    uint64_t i_v16 = *(int64_t *)i_v13;      // 0x11e5c
    uint64_t i_v17 = i_v16 / 0x100000000;    // 0x11e5c
    uint32_t i_v18 = *p_v2;                  // 0x11e68
    uint64_t i_v19 = i_v17 * (int64_t)i_v18; // 0x11e80
    int32_t i_v20 = i_v15 * (int32_t)i_v17 + i_v18 * (int32_t)i_v16 +
                    (int32_t)(i_v19 / 0x100000000); // 0x11e84
    int32_t i_v21 = i_v1 - 108;                     // 0x11e8c
    *(int32_t *)i_v21 = (int32_t)i_v19;
    *(int32_t *)(i_v1 - 104) = i_v20;
    uint32_t i_v22 = function_114c8(*p_v9 - 24 + *p_v6);     // 0x11ea8
    uint64_t i_v23 = *(int64_t *)(i_v1 - 84);                // 0x11eac
    uint32_t i_v24 = i_v22 + (int32_t)(i_v23 / 0x100000000); // 0x11eb0
    int32_t i_v25 = i_v1 - 164;                              // 0x11eb4
    *(int32_t *)i_v25 = i_v24;
    *(int32_t *)(i_v1 - 160) =
        i_v20 + (int32_t)i_v23 + (int32_t)(i_v24 < i_v22);
    int32_t i_v26 = *p_v14;                  // 0x11ec0
    uint64_t i_v27 = *(int64_t *)i_v25;      // 0x11ec4
    uint64_t i_v28 = i_v27 / 0x100000000;    // 0x11ec4
    uint32_t i_v29 = *p_v2;                  // 0x11ed0
    uint64_t i_v30 = i_v28 * (int64_t)i_v29; // 0x11ee8
    int32_t i_v31 = i_v1 - 116;              // 0x11ef4
    *(int32_t *)i_v31 = (int32_t)i_v30;
    *(int32_t *)(i_v1 - 112) = i_v26 * (int32_t)i_v28 + i_v29 * (int32_t)i_v27 +
                               (int32_t)(i_v30 / 0x100000000);
    uint64_t i_v32 = *(int64_t *)i_v5;                       // 0x11efc
    uint32_t i_v33 = (int32_t)(i_v32 / 0x100000000);         // 0x11efc
    int64_t *p_v34 = (int64_t *)i_v8;                        // 0x11f00
    uint64_t i_v35 = *p_v34;                                 // 0x11f00
    uint32_t i_v36 = (int32_t)(i_v35 / 0x100000000) + i_v33; // 0x11f04
    int32_t i_v37 = i_v1 - 172;                              // 0x11f08
    *(int32_t *)i_v37 = i_v36;
    *(int32_t *)(i_v1 - 168) =
        (int32_t)i_v35 + (int32_t)i_v32 + (int32_t)(i_v36 < i_v33);
    int64_t i_v38 = *(int64_t *)i_v37;                               // 0x11f18
    int32_t i_v39 = i_v38;                                           // 0x11f18
    uint32_t i_v40 = function_1154c(i_v38 >> 32, i_v39, 43);         // 0x11f1c
    int64_t i_v41 = *(int64_t *)i_v21;                               // 0x11f2c
    int32_t i_v42 = i_v41;                                           // 0x11f2c
    uint32_t i_v43 = function_1154c(i_v41 >> 32, i_v42, 30) + i_v40; // 0x11f3c
    int32_t i_v44 = i_v1 - 180;                                      // 0x11f40
    *(int32_t *)i_v44 = i_v43;
    *(int32_t *)(i_v1 - 176) = i_v42 + i_v39 + (int32_t)(i_v43 < i_v40);
    uint64_t i_v45 = *(int64_t *)i_v31;                      // 0x11f4c
    uint64_t i_v46 = *(int64_t *)i_v44;                      // 0x11f50
    uint32_t i_v47 = (int32_t)(i_v46 / 0x100000000);         // 0x11f50
    uint32_t i_v48 = i_v47 + (int32_t)(i_v45 / 0x100000000); // 0x11f58
    *(int32_t *)(i_v1 - 188) = i_v48;
    *(int32_t *)(i_v1 - 184) =
        (int32_t)i_v46 + (int32_t)i_v45 + (int32_t)(i_v48 < i_v47);
    uint64_t i_v49 = *p_v34;                                 // 0x11f68
    int32_t i_v50 = i_v49;                                   // 0x11f68
    int32_t i_v51 = i_v49 / 0x100000000;                     // 0x11f68
    uint64_t i_v52 = *(int64_t *)(i_v1 - 44);                // 0x11f6c
    uint32_t i_v53 = (int32_t)(i_v52 / 0x100000000) + i_v51; // 0x11f70
    *(int32_t *)(i_v1 - 196) = i_v53;
    *(int32_t *)(i_v1 - 192) =
        (int32_t)i_v52 + i_v50 + (int32_t)(i_v53 < i_v51);
    return function_11f90((int64_t)i_v51, (int64_t)i_v50, 18);
}

// Address range: 0x11f88 - 0x11f90
int32_t function_11f88(void) {
    // 0x11f88
    bool i_v1; // 0x11f88
    if (i_v1) {
        __asm_svchs(0x90404f);
    }
    int32_t i_v2; // 0x11f88
    return i_v2;
}

// Address range: 0x11f90 - 0x11ff4
int32_t function_11f90(int64_t i_a1, int64_t i_a2, int32_t i_a3) {
    // 0x11f90
    int32_t i_v1;                                           // 0x11f90
    int64_t i_v2 = *(int64_t *)(i_v1 - 196);                // 0x11f90
    int32_t i_v3 = i_v2;                                    // 0x11f90
    uint32_t i_v4 = function_1154c(i_v2 >> 32, i_v3, i_a3); // 0x11f94
    uint64_t i_v5 = *(int64_t *)(i_v1 - 92);                // 0x11f98
    uint32_t i_v6 = i_v4 + (int32_t)(i_v5 / 0x100000000);   // 0x11f9c
    int32_t i_v7 = i_v1 - 204;                              // 0x11fa0
    *(int32_t *)i_v7 = i_v6;
    *(int32_t *)(i_v1 - 200) = (int32_t)i_v5 + i_v3 + (int32_t)(i_v6 < i_v4);
    uint64_t i_v8 = *(int64_t *)(i_v1 - 108);               // 0x11fac
    uint64_t i_v9 = *(int64_t *)i_v7;                       // 0x11fb0
    uint32_t i_v10 = (int32_t)(i_v9 / 0x100000000);         // 0x11fb0
    uint32_t i_v11 = i_v10 + (int32_t)(i_v8 / 0x100000000); // 0x11fb8
    int32_t i_v12 = i_v1 - 212;                             // 0x11fbc
    *(int32_t *)i_v12 = i_v11;
    *(int32_t *)(i_v1 - 208) =
        (int32_t)i_v9 + (int32_t)i_v8 + (int32_t)(i_v11 < i_v10);
    uint64_t i_v13 = *(int64_t *)(i_v1 - 36); // 0x11fc8
    int64_t i_v14 = *(int64_t *)i_v12;        // 0x11fd0
    int64_t i_v15 = *(int64_t *)(i_v1 - 188); // 0x11fd4
    return function_115d0(i_v15 >> 32, (int32_t)i_v15, i_v14 >> 32,
                          (int32_t)i_v14, (int32_t)(i_v13 / 0x100000000),
                          (int32_t)i_v13);
}

// Address range: 0x11ff4 - 0x12114
int32_t function_11ff4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    // 0x11ff4
    int64_t i_v1; // 0x11ff4
    int32_t i_v2 =
        ((i_a3 >> 31) + (int32_t)(i_v1 / 0x100000000)) / 0x80000000; // 0x12020
    int32_t i_v3 = i_v1 / 0x100000000;                               // 0x1202c
    int32_t i_v4 = (int32_t)(i_v1 / 0x100000000) + i_v3 + i_v2;      // 0x12030
    int32_t i_v5 = function_1154c((int64_t)(i_v4 >> 31), i_v4, 21);  // 0x12048
    int32_t i_v6 = (i_v2 + (i_a5 >> 31)) / 0x80000000 +
                       (int32_t)((uint64_t)i_v1 / 0x100000000) >>
                   31;
    uint32_t i_v7 =
        ((i_v5 >> 31) + function_1154c((int64_t)i_v6, i_v6, 44)) / 0x80000000;
    int32_t i_v8 = i_v6 + i_v3;  // 0x120c8
    uint32_t i_v9 = i_v7 + i_v2; // 0x120e8
    *(int32_t *)i_a1 = i_v8 >> 31;
    *(int32_t *)(i_a1 + 4) = i_v8;
    *(int32_t *)(i_a1 + 8) = i_v9;
    *(int32_t *)(i_a1 + 12) = i_v9 + (int32_t)(i_v9 < i_v7);
    return i_a1;
}

// Address range: 0x12114 - 0x121b8
int32_t function_12114(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    int32_t i_v1 = (int32_t)p_a1;
    int32_t i_v2 = function_114c8(i_a2);     // 0x12130
    int32_t i_v3 = function_114c8(i_a2 + 8); // 0x12148
    function_114c8(i_a2 + 16);
    function_114c8(i_a2 + 24);
    function_11ff4(i_v1, i_a2, i_v2, i_a2, i_v3);
    return i_v1;
}

// Address range: 0x121b8 - 0x12c6c
int32_t function_121b8(int32_t i_a1, uint32_t i_a2, int32_t i_a3) {
    // 0x121b8
    if (i_a2 >= 16 != i_a2 != 16) {
        // 0x12c5c
        return function_11700(i_a1, i_a2);
    }
    // 0x121fc
    if (i_a2 >= 32 != i_a2 != 32 || i_a2 >= 64 != i_a2 != 64) {
        // 0x12c5c
        return i_a1;
    }
    int32_t i_v1 = function_11500(0x413964a1, -0x709bf205); // 0x122c0
    int64_t i_v2 = 0;                                       // bp-96, 0x122f4
    int64_t i_v3 = 0;                                       // bp-112, 0x1230c
    int32_t i_v4 = function_114c8(i_a1);                    // 0x1234c
    int32_t i_v5 = (i_a2 - 1 & -64) + i_a1;                 // 0x12374
    i_v2 = 0;
    int32_t i_v6 = i_a1;       // 0x12394
    int32_t i_v7 = i_v4 >> 31; // 0x12394
    int32_t i_v8 = 0;          // 0x12394
    int32_t i_v9 = ((i_v8 + i_v7 >> 31) +
                    (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000)) /
                       0x80000000 +
                   function_114c8(i_v6 + 8);                         // 0x123ec
    int32_t i_v10 = function_1154c((int64_t)(i_v9 >> 31), i_v9, 37); // 0x12404
    int32_t i_v11 = function_114c8(i_v6 + 48) + i_v8;                // 0x12468
    int32_t i_v12 =
        function_1154c((int64_t)(i_v11 >> 31), i_v11, 42); // 0x12480
    int32_t i_v13 = -0x4b6d4991 * i_v10 >> 31;
    i_v8 = ((function_114c8(i_v6 + 40) +
                 (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000) >>
             31) +
            (-0x4b6d4991 * i_v12 >> 31)) /
           0x80000000;
    int32_t i_v14 =
        (-0x651e95c5 * i_v1 >> 31) +
        (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000); // 0x12530
    int32_t i_v15 = -0x4b6d4991 * function_1154c((int64_t)(i_v14 >> 31), i_v14,
                                                 33); // 0x12560
    function_12114(
        (int32_t *)&i_v2, i_v6, 0, 0,
        i_v13 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000) >> 31);
    int32_t i_v16 = i_v15 >> 31;               // 0x125f4
    int32_t i_v17 = function_114c8(i_v6 + 16); // 0x12614
    function_12114((int32_t *)&i_v3, i_v6 + 32, i_v16, i_v16,
                   i_v8 + i_v17 >> 31);
    int32_t i_v18 =
        (0x100000000 * (int64_t)(i_v15 ^ i_v13) >> 63) / 0x100000000; // 0x12660
    i_v7 = (i_v13 ^ i_v18) >> 31;
    int32_t i_v19 = (i_v7 ^ i_v18) >> 31;
    i_v6 += 64;
    while (i_v6 != i_v5) {
        i_v9 = ((i_v8 + i_v7 >> 31) +
                (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000)) /
                   0x80000000 +
               function_114c8(i_v6 + 8);
        i_v10 = function_1154c((int64_t)(i_v9 >> 31), i_v9, 37);
        i_v11 = function_114c8(i_v6 + 48) + i_v8;
        i_v12 = function_1154c((int64_t)(i_v11 >> 31), i_v11, 42);
        i_v13 = -0x4b6d4991 * i_v10 >> 31;
        i_v8 = ((function_114c8(i_v6 + 40) +
                     (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000) >>
                 31) +
                (-0x4b6d4991 * i_v12 >> 31)) /
               0x80000000;
        i_v14 = i_v19 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000);
        i_v15 = -0x4b6d4991 * function_1154c((int64_t)(i_v14 >> 31), i_v14, 33);
        function_12114(
            (int32_t *)&i_v2, i_v6, 0, 0,
            i_v13 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000) >> 31);
        i_v16 = i_v15 >> 31;
        i_v17 = function_114c8(i_v6 + 16);
        function_12114((int32_t *)&i_v3, i_v6 + 32, i_v16, i_v16,
                       i_v8 + i_v17 >> 31);
        i_v18 = (0x100000000 * (int64_t)(i_v15 ^ i_v13) >> 63) / 0x100000000;
        i_v7 = (i_v13 ^ i_v18) >> 31;
        i_v19 = (i_v7 ^ i_v18) >> 31;
        i_v6 += 64;
    }
    int32_t i_v20 = (i_a2 + 63) % 64 - 63 + i_v5;             // 0x12390
    int32_t i_v21 = (0x100000000 * i_v3 >> 63) / 0x100000000; // 0x12784
    int32_t i_v22 =
        (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000) + i_v21 >> 31;
    i_v2 = i_v22;
    i_v3 = i_v22 + i_v21 >> 31;
    int32_t i_v23 = (i_v22 + (i_v7 + i_v8 >> 31)) / 0x80000000 +
                    function_114c8(i_v20 + 8); // 0x12818
    int32_t i_v24 =
        function_1154c((int64_t)(i_v23 >> 31), i_v23, 37); // 0x12834
    int32_t i_v25 = function_114c8(i_v20 + 48) + i_v8;     // 0x128a0
    int32_t i_v26 =
        function_1154c((int64_t)(i_v25 >> 31), i_v25, 42); // 0x128bc
    int32_t i_v27 = -1 * i_v24 >> 31;
    uint64_t i_v28 = (0x100000000 * i_v2 >> 32) / 0x100000000; // 0x12950
    int32_t i_v29 = ((8 * (int32_t)i_v28 + (int32_t)i_v28 >> 31) +
                     function_114c8(i_v20 + 40)) /
                            0x80000000 +
                        (-1 * i_v26 >> 31) >>
                    31;
    int32_t i_v30 =
        i_v19 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000); // 0x129f0
    int32_t i_v31 =
        function_1154c((int64_t)(i_v30 >> 31), i_v30, 33); // 0x12a0c
    int64_t i_v32;                                         // bp-136, 0x121b8
    function_12114(
        (int32_t *)&i_v32, i_v20, 0, 0,
        i_v27 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000) >> 31);
    i_v2 = 0x100000000 * i_v32 >> 32;
    int32_t i_v33 = -1 * i_v31 >> 31;
    int32_t i_v34 = function_114c8(i_v20 + 16); // 0x12ad8
    function_12114((int32_t *)&i_v32, i_v20 + 32, i_v33, i_v33,
                   i_v29 + i_v34 >> 31);
    int64_t i_v35 = 0x100000000 * i_v32;
    i_v3 = i_v35 >> 32;
    int64_t i_v36 = i_v2; // 0x12b8c
    int32_t i_v37 =
        function_115d0(0x100000000 * i_v36 >> 63, (int32_t)i_v36, i_v35 >> 63,
                       (int32_t)i_v32, -1, -1); // 0x12ba4
    int32_t i_v38 =
        (-0x3c5a37a4 * function_11500((int64_t)i_v29, i_v29) + i_v37 >> 31) +
        i_v27;                                 // 0x12bf8
    int64_t i_v39;                             // 0x121b8
    int32_t i_v40 = i_v39;                     // 0x12c08
    int64_t i_v41 = 0x100000000 * i_v39 >> 63; // 0x12c20
    int32_t i_v42 =
        function_115d0(i_v41, i_v40, i_v41, i_v40, -1, -1) + i_v33; // 0x12c28
    // 0x12c5c
    return function_115d0((int64_t)(i_v38 >> 31), i_v38, (int64_t)(i_v42 >> 31),
                          i_v42, -1, -1);
}

// Address range: 0x12c6c - 0x12c7a
int32_t function_12c6c(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = unknown_4132b0();       // 0x12c6c
    int32_t i_v2 = *(int32_t *)(i_v1 + 4); // 0x12c74
    *(int32_t *)i_v2 = i_v1 + 16;
    *(int32_t *)(i_v2 + 4) = *(int32_t *)i_v1;
    return -0x1d724ffc;
}

// Address range: 0x12c80 - 0x137e0
int32_t function_12c80(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x12c80
    int32_t i_v1;                             // 0x12c80
    int32_t *p_v2 = (int32_t *)(i_v1 - 3064); // 0x12c88
    *p_v2 = i_a1;
    int32_t *p_v3 = (int32_t *)(i_v1 - 3068); // 0x12c8c
    *p_v3 = i_a2;
    int32_t *p_v4 = (int32_t *)(i_v1 - 3072); // 0x12c90
    *p_v4 = i_a3;
    int32_t *p_v5 = (int32_t *)(i_v1 - 3076); // 0x12c94
    *p_v5 = i_a4;
    function_13c04(*p_v2, i_v1 - 196);
    uint32_t i_v6 =
        (int32_t)(*(int64_t *)(i_v1 - 148) / 0x100000000); // 0x12ca8
    int32_t *p_v7 = (int32_t *)(i_v1 - 32);                // 0x12cb0
    *p_v7 = i_v6;
    int32_t i_v8 = *p_v2;
    if (i_v6 <= 2047) {
        // 0x12cc0
        function_107e4("File '%s' Not Enough %d, Something Wrong!\n", i_v8,
                       2048, i_v6);
        // 0x137d4
        return 6;
    }
    int32_t i_v9 = function_107c0(i_v8, "rb", i_v6, (int32_t *)i_v6); // 0x12ce8
    int32_t *p_v10 = (int32_t *)(i_v1 - 36);                          // 0x12cec
    *p_v10 = i_v9;
    if (i_v9 == 0) {
        // 0x12cfc
        function_107e4("Read File '%s' Failed!\n", *p_v2, i_v6, 0);
        // 0x137d4
        return 7;
    }
    // 0x12d14
    function_10854((int32_t *)*p_v5, 2048, 1, i_v9);
    unsigned char i_v11 = *(char *)*p_v5; // 0x12d2c
    int32_t i_v12 = i_v11;                // 0x12d2c
    if (i_v11 != 38) {
        // 0x12d38
        function_107e4("'%s' Not A Btmu File!\n", *p_v2, 1, i_v12);
        int32_t i_v13 = *p_v10; // 0x12d48
        if (i_v13 != 0) {
            // 0x12d54
            function_10760(i_v13);
        }
        // 0x137d4
        return 8;
    }
    // 0x12d64
    function_107e4("miner_type %s\n", *p_v3, 1, i_v12);
    int32_t i_v14 = function_107a8((int32_t *)*p_v3); // 0x12d78
    int32_t i_v15 = function_121b8(*p_v3, i_v14, 1);  // 0x12d88
    int32_t i_v16 = i_v1 - 44;                        // 0x12d8c
    *(int32_t *)i_v16 = i_v15;
    *(int32_t *)(i_v1 - 40) = i_v14;
    int32_t i_v17 = *p_v5 + 2;         // 0x12d94
    int32_t i_v18 = i_v1 - 204;        // 0x12d98
    int32_t *p_v19 = (int32_t *)i_v18; // 0x12da4
    function_107b4(p_v19, i_v17, 8, p_v19);
    int64_t *p_v20 = (int64_t *)i_v16; // 0x12db0
    uint64_t i_v21 = *p_v20;           // 0x12db0
    function_107e4("miner_type_hash %16llx, bmu_hash %16llx\n", i_v17,
                   (int32_t)(i_v21 / 0x100000000), (int32_t)i_v21);
    uint64_t i_v22 = *(int64_t *)i_v18;  // 0x12dc0
    int32_t i_v23 = i_v22;               // 0x12dc0
    int32_t i_v24 = i_v22 / 0x100000000; // 0x12dc0
    uint64_t i_v25 = *p_v20;             // 0x12dc4
    int32_t i_v26 = i_v25;               // 0x12dc4
    if (i_v26 == i_v23) {
        if ((int32_t)(i_v25 / 0x100000000) == i_v24) {
            char *p_v27 = (char *)(i_v1 - 5); // 0x12e00
            *p_v27 = 0;
            int32_t i_v28 =
                __asm_sxth(256 * (int32_t) * (char *)(*p_v5 + 11)); // 0x12e10
            uint32_t i_v29 =
                __asm_sxth(__asm_sxth((int32_t) * (char *)(*p_v5 + 12)) |
                           i_v28);                   // 0x12e24
            int16_t *p_v30 = (int16_t *)(i_v1 - 46); // 0x12e28
            *p_v30 = (int16_t)i_v29;
            if (*(char *)(i_v1 + 12) != 0) {
                uint32_t i_v31 = i_v29 % 0x10000; // 0x12e38
                function_107e4("content:%x\n", i_v31, i_v28, i_v31);
                uint16_t i_v32 = *p_v30; // 0x12e4c
                if (i_v32 <= 0xfdff) {
                    // 0x12e5c
                    function_10818("This Package Was Not Full Package!", i_v31,
                                   i_v28, (int32_t)(i_v32 & -512));
                    // 0x137d4
                    return 20;
                }
            }
            int32_t *p_v33 = (int32_t *)(i_v1 - 12); // 0x12e74
            *p_v33 = 0;
            int32_t i_v34 = 0;     // 0x12ea4
            int32_t i_v35 = i_v34; // 0x12e90
            if ((1 << i_v34 & (int32_t)*p_v30) != 0) {
                // 0x12e94
                *p_v27 = *p_v27 + 1;
                i_v35 = *p_v33;
            }
            // 0x12ea0
            i_v34 = i_v35 + 1;
            *p_v33 = i_v34;
            while (i_v34 < 16) {
                // 0x12e7c
                i_v35 = i_v34;
                if ((1 << i_v34 & (int32_t)*p_v30) != 0) {
                    // 0x12e94
                    *p_v27 = *p_v27 + 1;
                    i_v35 = *p_v33;
                }
                // 0x12ea0
                i_v34 = i_v35 + 1;
                *p_v33 = i_v34;
            }
            unsigned char i_v36 = *(char *)(*p_v5 + 1304); // 0x12ebc
            unsigned char i_v37 = *p_v27;                  // 0x12ec0
            int32_t i_v38 = i_v36;
            if (i_v37 != i_v36) {
                int32_t i_v39 = i_v37; // 0x12ed8
                function_107e4("Content Doesn't Match![%d][%d]\n", i_v38, i_v39,
                               i_v39);
                int32_t i_v40 = *p_v10; // 0x12eec
                if (i_v40 != 0) {
                    // 0x12ef8
                    function_10760(i_v40);
                }
                // 0x137d4
                return 9;
            }
            int32_t *p_v41 = (int32_t *)(i_v1 - 16); // 0x12f18
            *p_v41 = 256 * i_v38 + 2304;
            int32_t i_v42 = *p_v5;                         // 0x12f1c
            unsigned char i_v43 = *(char *)(i_v42 + 1305); // 0x12f20
            unsigned char i_v44 = *(char *)(i_v42 + 1306); // 0x12f2c
            unsigned char i_v45 = *(char *)(i_v42 + 1307); // 0x12f3c
            unsigned char i_v46 = *(char *)(i_v42 + 1308); // 0x12f4c
            int32_t *p_v47 = (int32_t *)(i_v1 - 52);       // 0x12f54
            *p_v47 = 0x10000 * (int32_t)i_v44 | 0x1000000 * (int32_t)i_v43 |
                     256 * (int32_t)i_v45 | (int32_t)i_v46;
            int32_t *p_v48 = (int32_t *)(i_v1 - 20); // 0x12f5c
            *p_v48 = 0;
            if (*p_v27 != 0) {
                int32_t *p_v49 = (int32_t *)(i_v1 - 88);       // 0x13008
                int32_t i_v50 = *p_v5;                         // 0x12f78
                unsigned char i_v51 = *(char *)(i_v50 + 1310); // 0x12f84
                unsigned char i_v52 = *(char *)(i_v50 + 1311); // 0x12fac
                unsigned char i_v53 = *(char *)(i_v50 + 1312); // 0x12fd4
                unsigned char i_v54 = *(char *)(i_v50 + 1313); // 0x13000
                int32_t i_v55 =
                    0x10000 * (int32_t)i_v52 | 0x1000000 * (int32_t)i_v51 |
                    256 * (int32_t)i_v53 | (int32_t)i_v54; // 0x13004
                *p_v49 = i_v55;
                int32_t i_v56 = i_v55 + *p_v41; // 0x13014
                *p_v41 = i_v56;
                function_107e4("file[%d] size:[%d]\n", *p_v48, *p_v49, i_v56);
                int32_t i_v57 = *p_v48 + 1; // 0x13034
                *p_v48 = i_v57;
                while (i_v57 < (int32_t)*p_v27) {
                    // 0x12f64
                    i_v50 = *p_v5 + 5 * i_v57;
                    i_v51 = *(char *)(i_v50 + 1310);
                    i_v52 = *(char *)(i_v50 + 1311);
                    i_v53 = *(char *)(i_v50 + 1312);
                    i_v54 = *(char *)(i_v50 + 1313);
                    i_v55 = 0x10000 * (int32_t)i_v52 |
                            0x1000000 * (int32_t)i_v51 | 256 * (int32_t)i_v53 |
                            (int32_t)i_v54;
                    *p_v49 = i_v55;
                    i_v56 = i_v55 + *p_v41;
                    *p_v41 = i_v56;
                    function_107e4("file[%d] size:[%d]\n", *p_v48, *p_v49,
                                   i_v56);
                    i_v57 = *p_v48 + 1;
                    *p_v48 = i_v57;
                }
            }
            int32_t i_v58 = *p_v41; // 0x1304c
            int32_t i_v59 = *p_v7;  // 0x13050
            if (i_v58 != i_v59) {
                int32_t i_v60 = *p_v47; // 0x13064
                function_107e4(
                    "Check FileSize Failed, FileSize Should Be [%d]Bytes, But "
                    "It Was [%d] Bytes, And Total Says[%d]\n",
                    i_v60, i_v59, i_v58);
                int32_t i_v61 = *p_v10; // 0x13074
                if (i_v61 != 0) {
                    // 0x13080
                    function_10760(i_v61);
                }
                // 0x137d4
                return 10;
            }
            int32_t i_v62 =
                function_107c0(*p_v4, "r", i_v58, (int32_t *)i_v58); // 0x1309c
            int32_t *p_v63 = (int32_t *)(i_v1 - 56);                 // 0x130a0
            *p_v63 = i_v62;
            if (i_v62 == 0) {
                // 0x130b0
                function_107e4("Cannot Open Root PublicKey '%s'!\n", *p_v4,
                               i_v58, 0);
                int32_t i_v64 = *p_v10; // 0x130c0
                if (i_v64 != 0) {
                    // 0x130cc
                    function_10760(i_v64);
                }
                // 0x137d4
                return 11;
            }
            int32_t i_v65 = i_v1 - 1228;       // 0x130e0
            int32_t *p_v66 = (int32_t *)i_v65; // 0x130e0
            *p_v66 = 0;
            int32_t *p_v67 = (int32_t *)(i_v1 - 1224); // 0x130fc
            function_1076c(p_v67, 0, 1020, p_v67);
            function_10854(p_v66, 1024, 1, *p_v63);
            function_10760(*p_v63);
            *p_v63 = 0;
            int32_t i_v68 = *p_v5;                       // 0x1312c
            unsigned char i_v69 = *(char *)(i_v68 + 23); // 0x1313c
            int32_t i_v70 = 256 * (int32_t) * (char *)(i_v68 + 22) |
                            (int32_t)i_v69;          // 0x13140
            int32_t *p_v71 = (int32_t *)(i_v1 - 60); // 0x13144
            *p_v71 = i_v70;
            int32_t i_v72 = *p_v5;        // 0x13148
            int32_t i_v73 = i_v72 + 1048; // 0x1315c
            int32_t i_v74 =
                function_10ca8(i_v72 + 24, i_v70, i_v73, i_v65); // 0x1316c
            int32_t *p_v75 = (int32_t *)(i_v1 - 64);             // 0x13170
            *p_v75 = i_v74;
            if (i_v74 != 0) {
                // 0x13180
                function_107e4("Check pem payload failed! ret:[%d]\n", i_v74,
                               i_v73, i_v74);
                int32_t i_v76 = *p_v10; // 0x13190
                if (i_v76 != 0) {
                    // 0x1319c
                    function_10760(i_v76);
                }
                // 0x137d4
                return *p_v75;
            }
            char *p_v77 = (char *)(i_v1 + 4); // 0x131ac
            unsigned char i_v78 = *p_v77;     // 0x131ac
            if (i_v78 != 0) {
                int32_t i_v79 =
                    function_107c0((int32_t) "/tmp/tmpfw/miner.pem", "w", i_v73,
                                   (int32_t *)(int32_t)i_v78); // 0x131c8
                int32_t *p_v80 = (int32_t *)(i_v1 - 68);       // 0x131cc
                *p_v80 = i_v79;
                if (i_v79 == 0) {
                    // 0x13224
                    function_10818("Dump Miner.pem Failed!\r", (int32_t) "w",
                                   i_v73, 0);
                    // 0x137d4
                    return 15;
                }
                int32_t i_v81 = *p_v71; // 0x131e4
                function_107fc((int32_t *)(*p_v5 + 24), 1, i_v81, i_v79);
                function_10760(*p_v80);
                int32_t i_v82 =
                    function_107c0((int32_t) "/tmp/tmpfw/miner.pem.sig", "w",
                                   i_v81, (int32_t *)i_v79); // 0x1320c
                *p_v80 = i_v82;
                if (i_v82 == 0) {
                    // 0x13260
                    function_10818("Dump Miner.pem.sig Failed!\r",
                                   (int32_t) "w", i_v81, 0);
                    // 0x137d4
                    return 16;
                }
                // 0x13238
                function_107fc((int32_t *)(*p_v5 + 1048), 1, 256, i_v82);
                function_10760(*p_v80);
            }
            int32_t i_v83 = i_v1 - 2284;       // 0x1327c
            int32_t *p_v84 = (int32_t *)i_v83; // 0x1328c
            function_1076c(p_v84, 0, 1056, p_v84);
            int32_t *p_v85 = (int32_t *)(i_v1 - 2396); // 0x132a0
            function_10848(p_v85);
            function_10830(p_v85, *p_v5, 2048, p_v85);
            function_1079c(p_v84, p_v85, p_v85, p_v84);
            int32_t *p_v86 = (int32_t *)(i_v1 - 24); // 0x132e8
            *p_v86 = 0;
            if (*p_v27 != 0) {
                int32_t i_v87 = i_v1 - 2252;                   // 0x133a4
                int32_t i_v88 = *p_v5;                         // 0x13304
                unsigned char i_v89 = *(char *)(i_v88 + 1310); // 0x13310
                unsigned char i_v90 = *(char *)(i_v88 + 1311); // 0x13338
                unsigned char i_v91 = *(char *)(i_v88 + 1312); // 0x13360
                unsigned char i_v92 = *(char *)(i_v88 + 1313); // 0x1338c
                int32_t i_v93 =
                    0x10000 * (int32_t)i_v90 | 0x1000000 * (int32_t)i_v89 |
                    256 * (int32_t)i_v91 | (int32_t)i_v92; // 0x13390
                *(int32_t *)(i_v1 - 84) = i_v93;
                int32_t i_v94 = *p_v86; // 0x1339c
                unsigned char i_v95 =
                    *(char *)(5 * i_v94 + 1309 + *p_v5); // 0x133d8
                function_10e20(*p_v10, i_v93, i_v87 + 32 * i_v94,
                               (int32_t)i_v95, 0, (int32_t)*p_v77);
                int32_t i_v96 = *p_v86 + 1; // 0x13404
                *p_v86 = i_v96;
                while (i_v96 < (int32_t)*p_v27) {
                    // 0x132f0
                    i_v88 = *p_v5 + 5 * i_v96;
                    i_v89 = *(char *)(i_v88 + 1310);
                    i_v90 = *(char *)(i_v88 + 1311);
                    i_v91 = *(char *)(i_v88 + 1312);
                    i_v92 = *(char *)(i_v88 + 1313);
                    i_v93 = 0x10000 * (int32_t)i_v90 |
                            0x1000000 * (int32_t)i_v89 | 256 * (int32_t)i_v91 |
                            (int32_t)i_v92;
                    *(int32_t *)(i_v1 - 84) = i_v93;
                    i_v94 = *p_v86;
                    i_v95 = *(char *)(5 * i_v94 + 1309 + *p_v5);
                    function_10e20(*p_v10, i_v93, i_v87 + 32 * i_v94,
                                   (int32_t)i_v95, 0, (int32_t)*p_v77);
                    i_v96 = *p_v86 + 1;
                    *p_v86 = i_v96;
                }
            }
            int32_t *p_v97 = (int32_t *)(i_v1 - 28); // 0x13420
            *p_v97 = 0;
            unsigned char i_v98 = *p_v27; // 0x134a0
            if (i_v98 != 0) {
                int32_t i_v99 = 0; // 0x13498
                unsigned char i_v100 =
                    *(char *)(5 * i_v99 + 1309 + *p_v5); // 0x1346c
                unsigned char i_v101 = *p_v77;           // 0x13470
                int32_t i_v102 = *p_v10;                 // 0x1348c
                function_10e20(i_v102, 256,
                               32 * ((int32_t)i_v98 + 1 + i_v99) + i_v83,
                               (int32_t)i_v100, 1, (int32_t)i_v101);
                i_v99 = *p_v97 + 1;
                *p_v97 = i_v99;
                int32_t i_v103 = (int32_t)*p_v27; // 0x134a0
                while (i_v99 < i_v103) {
                    // 0x13428
                    i_v100 = *(char *)(5 * i_v99 + 1309 + *p_v5);
                    i_v101 = *p_v77;
                    i_v102 = *p_v10;
                    function_10e20(i_v102, 256,
                                   32 * (i_v103 + 1 + i_v99) + i_v83,
                                   (int32_t)i_v100, 1, (int32_t)i_v101);
                    i_v99 = *p_v97 + 1;
                    *p_v97 = i_v99;
                    i_v103 = (int32_t)*p_v27;
                }
            }
            int32_t i_v104 = i_v1 - 2652;        // 0x134b4
            int32_t *p_v105 = (int32_t *)i_v104; // 0x134b4
            *p_v105 = 0;
            int32_t *p_v106 = (int32_t *)(i_v1 - 2648); // 0x134d0
            function_1076c(p_v106, 0, 252, p_v106);
            function_10784(*p_v10, -256, 2);
            function_10854(p_v105, 256, 1, *p_v10);
            int32_t i_v107 = i_v1 - 2684;        // 0x13504
            int32_t *p_v108 = (int32_t *)i_v107; // 0x13504
            *p_v108 = 0;
            *(int32_t *)(i_v1 - 2680) = 0;
            *(int32_t *)(i_v1 - 2676) = 0;
            *(int32_t *)(i_v1 - 2672) = 0;
            *(int32_t *)(i_v1 - 2668) = 0;
            *(int32_t *)(i_v1 - 2664) = 0;
            *(int32_t *)(i_v1 - 2660) = 0;
            *(int32_t *)(i_v1 - 2656) = 0;
            int32_t *p_v109 = (int32_t *)(i_v1 - 2796); // 0x13544
            function_10848(p_v109);
            function_10830(p_v109, i_v83, 64 * (int32_t)*p_v27 | 32, p_v109);
            function_1079c(p_v108, p_v109, p_v109, p_v108);
            int32_t *p_v110 = (int32_t *)(i_v1 - 72); // 0x135a0
            *p_v110 = 0;
            int32_t *p_v111 = (int32_t *)(i_v1 - 76); // 0x135a8
            *p_v111 = 0;
            int32_t i_v112 = function_107cc(*p_v5 + 24, 1024); // 0x135bc
            *p_v110 = i_v112;
            int32_t i_v113 = function_10790(i_v112, 0, 0, 0); // 0x135d4
            *p_v111 = i_v113;
            if (i_v113 == 0) {
                int32_t i_v114 =
                    function_107f0(function_1073c(0), 0); // 0x135f8
                function_107e4("OpenSSL error: %s\n", i_v114, 0, i_v114);
                function_10818("Load Pem Failed!", i_v114, 0, i_v114);
                // 0x137d4
                return 17;
            }
            int32_t i_v115 =
                function_10778(672, p_v108, 32, i_v104, 256, i_v113); // 0x13654
            int32_t *p_v116 = (int32_t *)(i_v1 - 80);                 // 0x13658
            *p_v116 = i_v115;
            int32_t i_v117 = *p_v111; // 0x1365c
            if (i_v117 != 0) {
                // 0x13668
                function_10824(i_v117);
            }
            int32_t i_v118 = *p_v110; // 0x13670
            if (i_v118 != 0) {
                // 0x1367c
                function_1083c(i_v118);
            }
            int32_t i_v119 = *p_v116; // 0x13684
            if (i_v119 != 1) {
                int32_t i_v120 = function_10818("Check File Sig failed!\r",
                                                i_v107, 32, i_v119); // 0x13698
                int32_t i_v121 =
                    function_107f0(function_1073c(i_v120), 0); // 0x136ac
                function_107e4("OpenSSL error: %s\n", i_v121, 32, i_v121);
                // 0x137d4
                return 18;
            }
            int32_t i_v122 = *p_v10; // 0x136cc
            if (i_v122 != 0) {
                // 0x136d8
                function_10760(i_v122);
            }
            // 0x136e0
            *p_v10 = 0;
            unsigned char i_v123 = *(char *)(i_v1 + 8); // 0x136e8
            int32_t i_v124 = 32;                        // 0x136f0
            if (i_v123 != 0) {
                // 0x136f4
                function_10818("This Comment Of This Package:", i_v107, 32,
                               (int32_t)i_v123);
                int32_t i_v125 = i_v1 - 3056;        // 0x13704
                int32_t *p_v126 = (int32_t *)i_v125; // 0x13704
                *p_v126 = 0;
                int32_t *p_v127 = (int32_t *)(i_v1 - 3052); // 0x13720
                function_1076c(p_v127, 0, 253, p_v127);
                int32_t i_v128 = *p_v5 + 1360; // 0x13728
                function_107b4(p_v126, i_v128, 256, p_v126);
                function_10818((char *)i_v125, i_v128, 256, i_v125);
                i_v124 = 256;
            }
            int32_t i_v129 = *p_v5; // 0x13758
            if (i_v129 == -13) {
                // 0x137d4
                return 0;
            }
            int32_t i_v130 = i_v129 + 13; // 0x1376c
            function_107e4("fwVer: %s\r\n", i_v130, i_v124, i_v130);
            int32_t i_v131 = function_10860(*p_v5 + 13, "sweep", 5); // 0x13798
            int32_t i_v132;                                          // 0x12c80
            if (i_v131 == 0) {
                // 0x137bc
                function_10818("All Done! this is a sweep version! \r",
                               (int32_t) "sweep", 5, 0);
                i_v132 = 100;
            } else {
                // 0x137a8
                function_10818("All Done! this is not a sweep version! \r",
                               (int32_t) "sweep", 5, i_v131);
                i_v132 = 0;
            }
            // 0x137d4
            return i_v132;
        }
    }
    // 0x12dd4
    function_10818("input miner_type and bmu miner type donot match!", i_v26,
                   i_v24, i_v23);
    int32_t i_v133 = *p_v10; // 0x12de0
    if (i_v133 != 0) {
        // 0x12dec
        function_10760(i_v133);
    }
    // 0x137d4
    return 30;
}

// Address range: 0x137e0 - 0x13bc4
int32_t function_137e0(uint32_t i_a1, int32_t i_a2) {
    // 0x137e0
    if (i_a1 <= 1) {
        // 0x13bb8
        return 1;
    }
    int32_t *p_v1 = (int32_t *)(i_a2 + 4); // 0x13824
    if (*(char *)*p_v1 != 45) {
        // 0x13bb8
        return 2;
    }
    int32_t i_v2 = 0; // bp-272, 0x13850
    int32_t i_v3;     // bp-268, 0x137e0
    function_1076c(&i_v3, 0, 252, &i_v3);
    int32_t i_v4 = 0; // bp-400, 0x1386c
    int32_t i_v5;     // bp-396, 0x137e0
    function_1076c(&i_v5, 0, 124, &i_v5);
    int32_t i_v6 = 0; // bp-528, 0x13888
    int32_t i_v7;     // bp-524, 0x137e0
    function_1076c(&i_v7, 0, 124, &i_v7);
    int32_t i_v8; // bp-2576, 0x137e0
    function_1076c(&i_v8, 0, 2048, &i_v8);
    int32_t i_v9; // bp-2832, 0x137e0
    function_1076c(&i_v9, 0, 253, &i_v9);
    int32_t i_v10 = 0;   // 0x137e0
    int32_t i_v11 = 253; // 0x137e0
    switch (i_a1) {
    case 5: {
        int32_t *p_v12 = (int32_t *)(i_a2 + 8);             // 0x1390c
        uint32_t i_v13 = function_107a8((int32_t *)*p_v12); // 0x13914
        if (i_v13 != 255 && i_v13 >= 255) {
            // 0x13924
            function_10818("fileName Too Long!", 0, 253, i_v13);
            // 0x13bb8
            return 3;
        }
        int32_t i_v14 = *p_v12; // 0x13940
        function_107d8(&i_v2, i_v14);
        int32_t *p_v15 = (int32_t *)(i_a2 + 12);            // 0x1395c
        uint32_t i_v16 = function_107a8((int32_t *)*p_v15); // 0x13964
        if (i_v16 != 127 && i_v16 >= 127) {
            // 0x13974
            function_10818("fileName Too Long!", i_v14, i_v14, i_v16);
            // 0x13bb8
            return 3;
        }
        int32_t i_v17 = *p_v15; // 0x13990
        function_107d8(&i_v4, i_v17);
        int32_t *p_v18 = (int32_t *)(i_a2 + 16);            // 0x139ac
        uint32_t i_v19 = function_107a8((int32_t *)*p_v18); // 0x139b4
        if (i_v19 != 127 && i_v19 >= 127) {
            // 0x139c4
            function_10818("pemName Too Long!", i_v17, i_v17, i_v19);
            // 0x13bb8
            return 4;
        }
        int32_t i_v20 = *p_v18; // 0x139e0
        function_107d8(&i_v6, i_v20);
        i_v10 = i_v20;
        i_v11 = i_v20;
    }
    case 2: {
    lab_0x13a88:;
        unsigned char i_v21 = *(char *)(*p_v1 + 1); // 0x13aa0
        int32_t i_v22 = (int32_t)i_v21 - 102;       // 0x13aa4
        i_g6 = i_v22;
        int32_t i_v23; // 0x137e0
        switch (i_v21) {
        case 102: {
        }
        case 120: {
        }
        case 115: {
        }
        case 112: {
            // 0x13b30
            i_v23 = &i_v4;
            // break -> 0x13bb8
            break;
        }
        case 113: {
            // 0x13b84
            i_v23 = function_10bd4();
            // break -> 0x13bb8
            break;
        }
        case 110: {
            // 0x13b70
            i_v23 = function_109e0(&i_v4);
            // break -> 0x13bb8
            break;
        }
        default: {
            // 0x13b90
            function_10818("Command Not Support!", i_v10, i_v11, i_v22);
            i_v23 = 5;
            // break -> 0x13bb8
            break;
        }
        }
        // 0x13bb8
        return i_v23;
    }
    case 3: {
        int32_t *p_v24 = (int32_t *)(i_a2 + 8);             // 0x13a0c
        uint32_t i_v25 = function_107a8((int32_t *)*p_v24); // 0x13a14
        if (i_v25 != 127 && i_v25 >= 127) {
            // 0x13a24
            function_10818("fileName Too Long!", 0, 253, i_v25);
            // 0x13bb8
            return 3;
        }
        int32_t i_v26 = *p_v24; // 0x13a40
        function_107d8(&i_v4, i_v26);
        i_v10 = i_v26;
        i_v11 = i_v26;
        // branch (via goto) -> 0x13a88
        goto lab_0x13a88;
    }
    default: {
        // 0x13a64
        function_10818("Param Err!", 0, 253, i_a1);
        // 0x13bb8
        return 3;
    }
    }
}

// Address range: 0x13bc4 - 0x13bf8
int32_t function_13bc4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_10710(i_a1, i_a2, i_a3, i_a4); // 0x13bd4
    return 0x24f0a - (int32_t)&i_g1 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x13c00 - 0x13c02
int32_t function_13c00(void) {
    // 0x13c00
    int32_t i_v1; // 0x13c00
    return i_v1;
}

// Address range: 0x13c04 - 0x13c08
int32_t function_13c04(int32_t i_a1, int32_t i_a2) {
    // 0x13c04
    bool i_v1; // 0x13c04
    if (i_v1) {
        // branch ->
    }
    return i_a1;
}

// Address range: 0x13c08 - 0x13c0e
int32_t function_13c08(void) {
    // 0x13c08
    return function_10808();
}

// Address range: 0x13c10 - 0x13c18
int32_t function_13c10(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x13c10
    return i_a1;
}

// Address range: 0xe0832002 - 0xe0832003
int32_t function_e0832002(void) {
    // 0xe0832002
    int32_t i_v1; // 0xe0832002
    return i_v1;
}

// Address range: 0xe1a00003 - 0xe1a00004
int32_t function_e1a00003(void) {
    // 0xe1a00003
    int32_t i_v1; // 0xe1a00003
    return i_v1;
}

// Address range: 0xe1a02003 - 0xe1a02004
int32_t function_e1a02003(void) {
    // 0xe1a02003
    int32_t i_v1; // 0xe1a02003
    return i_v1;
}

// Address range: 0xe1a03000 - 0xe1a03001
int32_t function_e1a03000(void) {
    // 0xe1a03000
    int32_t i_v1; // 0xe1a03000
    return i_v1;
}

// Address range: 0xe1a0c003 - 0xe1a0c004
int32_t function_e1a0c003(void) {
    // 0xe1a0c003
    int32_t i_v1; // 0xe1a0c003
    return i_v1;
}

// Address range: 0xe1a0e002 - 0xe1a0e003
int32_t function_e1a0e002(void) {
    // 0xe1a0e002
    int32_t i_v1; // 0xe1a0e002
    return i_v1;
}

// Address range: 0xe2433004 - 0xe2433005
int32_t function_e2433004(void) {
    // 0xe2433004
    int32_t i_v1; // 0xe2433004
    return i_v1;
}

// Address range: 0xe243300c - 0xe243300d
int32_t function_e243300c(void) {
    // 0xe243300c
    int32_t i_v1; // 0xe243300c
    return i_v1;
}

// Address range: 0xe24b3e51 - 0xe24b3e52
int32_t function_e24b3e51(void) {
    // 0xe24b3e51
    int32_t i_v1; // 0xe24b3e51
    return i_v1;
}

// Address range: 0xe3033fa8 - 0xe3033fa9
int32_t function_e3033fa8(void) {
    // 0xe3033fa8
    int32_t i_v1; // 0xe3033fa8
    return i_v1;
}

// Address range: 0xe3033fbc - 0xe3033fbd
int32_t function_e3033fbc(void) {
    // 0xe3033fbc
    int32_t i_v1; // 0xe3033fbc
    return i_v1;
}

// Address range: 0xe3403001 - 0xe3403002
int32_t function_e3403001(void) {
    // 0xe3403001
    int32_t i_v1; // 0xe3403001
    return i_v1;
}

// Address range: 0xe58e0000 - 0xe58e0001
int32_t function_e58e0000(void) {
    // 0xe58e0000
    int32_t i_v1; // 0xe58e0000
    return i_v1;
}

// Address range: 0xe58e1004 - 0xe58e1005
int32_t function_e58e1004(void) {
    // 0xe58e1004
    int32_t i_v1; // 0xe58e1004
    return i_v1;
}

// Address range: 0xe58e2008 - 0xe58e2009
int32_t function_e58e2008(void) {
    // 0xe58e2008
    int32_t i_v1; // 0xe58e2008
    return i_v1;
}

// Address range: 0xe58e300c - 0xe58e300d
int32_t function_e58e300c(void) {
    // 0xe58e300c
    int32_t i_v1; // 0xe58e300c
    return i_v1;
}

// Address range: 0xe5ce3010 - 0xe5ce3011
int32_t function_e5ce3010(void) {
    // 0xe5ce3010
    int32_t i_v1; // 0xe5ce3010
    return i_v1;
}

// Address range: 0xe5dc3000 - 0xe5dc3001
int32_t function_e5dc3000(void) {
    // 0xe5dc3000
    int32_t i_v1; // 0xe5dc3000
    return i_v1;
}

// Address range: 0xe8bc000f - 0xe8bc0010
int32_t function_e8bc000f(void) {
    // 0xe8bc000f
    int32_t i_v1; // 0xe8bc000f
    return i_v1;
}

// Address range: 0xea000064 - 0xea000065
int32_t function_ea000064(void) {
    // 0xea000064
    int32_t i_v1; // 0xea000064
    return i_v1;
}

// Address range: 0xebfffdce - 0xebfffdcf
int32_t function_ebfffdce(void) {
    // 0xebfffdce
    int32_t i_v1; // 0xebfffdce
    return i_v1;
}

// Address range: 0xff86c500 - 0xff86c501
int32_t function_ff86c500(void) {
    // 0xff86c500
    int32_t i_v1; // 0xff86c500
    return i_v1;
}

// Address range: 0xff86c880 - 0xff86c881
int32_t function_ff86c880(void) {
    // 0xff86c880
    int32_t i_v1; // 0xff86c880
    return i_v1;
}

// Address range: 0xff86cea8 - 0xff86cea9
int32_t function_ff86cea8(void) {
    // 0xff86cea8
    int32_t i_v1; // 0xff86cea8
    return i_v1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 83
