//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <ctype.h>
#include <errno.h>
#include <netdb.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct hostent {
    char *e0;
    char **e1;
    int32_t e2;
    int32_t e3;
    char **e4;
};

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t __libc_csu_fini(void);
int32_t __libc_csu_init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _fini(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _start(int32_t i_a1, int32_t i_a2);
int32_t callapi(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t display(int32_t i_a1);
int32_t function_108b0(char *s1, char *s2);
int32_t function_108bc(char *nptr, char **endptr, int32_t base);
int32_t function_108c8(char *format, ...);
int32_t *function_108d4(int32_t *ptr, int32_t size);
int32_t *function_108e0(int32_t *s, int32_t c);
int32_t function_108ec(char *s);
int32_t *function_108f8(int32_t size);
int32_t function_10904(int32_t main2, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)());
char *function_10910(int32_t errnum);
void function_1091c(void);
int16_t **function_10928(void);
int32_t function_10934(char *s);
char *function_10940(char *s, int32_t c);
int32_t function_1094c(struct _IO_FILE *stream, char *format, ...);
int32_t *function_10958(void);
int32_t function_10964(int32_t domain, int32_t type, int32_t protocol);
struct hostent *function_10970(char *name);
void function_1097c(void);
int32_t function_10988(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_10994(int32_t fd);
int32_t function_109a0(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_109ac(int32_t fd, struct sockaddr *addr, int32_t len);
int32_t function_10b70(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10b7c(void);
int32_t function_10ba0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10bfc(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_10c08(void);
int32_t function_10c0c(int32_t i_a1);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

char *p_g1;                   // 0x110fc
int32_t i_g2 = 0x10c09;       // 0x21f10
int32_t i_g3 = 0;             // 0x22064
struct _IO_FILE *p_g4 = NULL; // 0x22070
int32_t i_g5 = 0;             // 0x22078
int32_t i_g6;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t i_a1, int32_t i_a2, char **p_a3,
                          void (*p_a4)(), void (*p_a5)(), void (*p_a6)());
int32_t *__rawmemchr(int32_t *p_a1, int32_t i_a2);

// ------------------------ Functions -------------------------

// Address range: 0x10890 - 0x1089c
int32_t _init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10890
    return function_10b7c();
}

// Address range: 0x108b0 - 0x108bc
int32_t function_108b0(char *s1, char *s2) {
    // 0x108b0
    return strcmp(s1, s2);
}

// Address range: 0x108bc - 0x108c8
int32_t function_108bc(char *nptr, char **endptr, int32_t base) {
    // 0x108bc
    return strtol(nptr, endptr, base);
}

// Address range: 0x108c8 - 0x108d4
int32_t function_108c8(char *format, ...) {
    // 0x108c8
    return printf(format);
}

// Address range: 0x108d4 - 0x108e0
int32_t *function_108d4(int32_t *ptr, int32_t size) {
    // 0x108d4
    return realloc(ptr, size);
}

// Address range: 0x108e0 - 0x108ec
int32_t *function_108e0(int32_t *s, int32_t c) {
    // 0x108e0
    return __rawmemchr(s, c);
}

// Address range: 0x108ec - 0x108f8
int32_t function_108ec(char *s) {
    // 0x108ec
    return puts(s);
}

// Address range: 0x108f8 - 0x10904
int32_t *function_108f8(int32_t size) {
    // 0x108f8
    return malloc(size);
}

// Address range: 0x10904 - 0x10910
int32_t function_10904(int32_t main2, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x10904
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x10910 - 0x1091c
char *function_10910(int32_t errnum) {
    // 0x10910
    return strerror(errnum);
}

// Address range: 0x1091c - 0x10928
void function_1091c(void) {
    // 0x1091c
    __gmon_start__();
}

// Address range: 0x10928 - 0x10934
int16_t **function_10928(void) {
    // 0x10928
    return __ctype_b_loc();
}

// Address range: 0x10934 - 0x10940
int32_t function_10934(char *s) {
    // 0x10934
    return strlen(s);
}

// Address range: 0x10940 - 0x1094c
char *function_10940(char *s, int32_t c) {
    // 0x10940
    return strchr(s, c);
}

// Address range: 0x1094c - 0x10958
int32_t function_1094c(struct _IO_FILE *stream, char *format, ...) {
    // 0x1094c
    return fprintf(stream, format);
}

// Address range: 0x10958 - 0x10964
int32_t *function_10958(void) {
    // 0x10958
    return __errno_location();
}

// Address range: 0x10964 - 0x10970
int32_t function_10964(int32_t domain, int32_t type, int32_t protocol) {
    // 0x10964
    return socket(domain, type, protocol);
}

// Address range: 0x10970 - 0x1097c
struct hostent *function_10970(char *name) {
    // 0x10970
    return gethostbyname(name);
}

// Address range: 0x1097c - 0x10988
void function_1097c(void) {
    // 0x1097c
    abort();
}

// Address range: 0x10988 - 0x10994
int32_t function_10988(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x10988
    return recv(fd, buf, n, flags);
}

// Address range: 0x10994 - 0x109a0
int32_t function_10994(int32_t fd) {
    // 0x10994
    return close(fd);
}

// Address range: 0x109a0 - 0x109ac
int32_t function_109a0(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x109a0
    return send(fd, buf, n, flags);
}

// Address range: 0x109ac - 0x109b8
int32_t function_109ac(int32_t fd, struct sockaddr *addr, int32_t len) {
    // 0x109ac
    return connect(fd, addr, len);
}

// Address range: 0x109b8 - 0x10b4c
int main(int argc, char **argv) {
    // 0x109b8
    if (argc < 2) {
        // 0x10ae0
        return callapi((int32_t) "summary", (int32_t) "127.0.0.1", 4028);
    }
    int32_t i_v1 = (int32_t)argv;
    int32_t i_v2 = *(int32_t *)(i_v1 + 4); // 0x109c4
    char *p_v3 = (char *)i_v2;             // 0x109d0
    char i_v4;                             // 0x10a6c
    if (*p_v3 == 45) {
        // 0x10a6c
        i_v4 = *(char *)(i_v2 + 1);
        switch (i_v4) {
        case 63: {
            // 0x10a78
            if (*(char *)(i_v2 + 2) == 0) {
                // 0x10b04
                fprintf(p_g4, "usAge: %s [command [ip/host [port]]]\n",
                        (char *)0x11a4);
                return 1;
            }
            goto lab_0x10a84;
        }
        case 104: {
            // 0x10af8
            if (*(char *)(i_v2 + 2) == 0) {
                // 0x10b04
            }
            goto lab_0x109dc;
        }
        default: {
            goto lab_0x10a84;
        }
        }
    } else {
        goto lab_0x109dc;
    }
lab_0x109dc:;
    int32_t i_v5 = 1; // 0x109f0
    if (strcmp(p_v3, "--help") == 0) {
        // 0x10b04
        fprintf(p_g4, "usAge: %s [command [ip/host [port]]]\n", (char *)0x11a4);
        return 1;
    }
    goto lab_0x109f8;
lab_0x10a84:
    // 0x10a84
    if (strcmp(p_v3, "--help") == 0) {
        // 0x10b04
        fprintf(p_g4, "usAge: %s [command [ip/host [port]]]\n", (char *)0x11a4);
        return 1;
    }
    // 0x10a9c
    i_v5 = 1;
    if (i_v4 == 111) {
        // 0x10aa4
        i_v5 = 1;
        if (*(char *)(i_v2 + 2) == 0) {
            // 0x10ab0
            i_g5 = 1;
            i_v5 = 2;
            if (argc == 2) {
                // 0x10ae0
                return callapi((int32_t) "summary", (int32_t) "127.0.0.1",
                               4028);
            }
        }
    }
    goto lab_0x109f8;
lab_0x109f8:;
    int32_t i_v6 = 4 * i_v5 + i_v1;                  // 0x109f8
    int32_t i_v7 = function_10c0c(*(int32_t *)i_v6); // 0x10a00
    int32_t i_v8 = *(char *)i_v7 == 0 ? (int32_t) "summary" : i_v7;
    if (i_v5 + 1 >= argc) {
        // 0x10ae0
        return callapi(i_v8, (int32_t) "127.0.0.1", 4028);
    }
    int32_t i_v9 = function_10c0c(*(int32_t *)(i_v6 + 4)); // 0x10a34
    int32_t i_v10 = *(char *)i_v9 == 0 ? (int32_t) "127.0.0.1" : i_v9;
    if (i_v5 + 2 >= argc) {
        // 0x10ae0
        return callapi(i_v8, i_v10, 4028);
    }
    char *p_v11 = (char *)function_10c0c(*(int32_t *)(i_v6 + 8)); // 0x10a58
    int32_t i_v12 = 4028;                                         // 0x10a60
    if (*p_v11 != 0) {
        // 0x10b28
        i_v12 = __asm_sxth(strtol(p_v11, NULL, 10));
    }
    // 0x10ae0
    return callapi(i_v8, i_v10, i_v12);
}

// Address range: 0x10b4c - 0x10b70
int32_t _start(int32_t i_a1, int32_t i_a2) {
    // 0x10b4c
    int32_t i_v1; // 0x10b4c
    __libc_start_main(0x109b8, i_a2, (char **)&i_v1, (void (*)())0x11061,
                      (void (*)())0x109b8, (void (*)())i_a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x10b70 - 0x10b74
int32_t function_10b70(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10b70
    return i_a1;
}

// Address range: 0x10b7c - 0x10b98
int32_t function_10b7c(void) {
    // 0x10b7c
    if (i_g3 == 0) {
        int32_t i_v1; // 0x10b7c
        return i_v1;
    }
    // 0x10b94
    __gmon_start__();
    return &i_g6;
}

// Address range: 0x10ba0 - 0x10bfc
int32_t function_10ba0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10ba0
    bool i_v1; // 0x10ba0
    if (i_v1) {
        return i_a1;
    }
    // 0x10bd0
    int32_t i_v2;                   // 0x10ba0
    int32_t i_v3 = 0x100001 * i_v2; // 0x10bd4
    bool i_v4;                      // 0x10ba0
    int32_t i_v5;                   // 0x10ba0
    if (i_v1) {
        // .thread
        i_v5 = i_v1 ? i_v3 : 0;
    } else {
        int32_t i_v6 = i_v3 & -1 - 0x400000 * i_v2; // 0x10bd8
        i_v5 = i_v6 < 1 ? 0 : i_v3;
        i_v4 = i_v6 < 0;
        if (i_v6 == 0) {
            return unknown_240();
        }
    }
    // 0x10be8
    if (i_v4 != i_v1) {
        __asm_svclt(0x4770);
    }
    float64_t f_v7; // 0x10ba0
    __asm_vqrshl_s8(f_v7, f_v7);
    __asm_vmvn_i32(0x40000);
    if (!i_v1) {
        *(int32_t *)i_a4 = i_v5;
    }
    return i_a1;
}

// Address range: 0x10bfc - 0x10c08
int32_t function_10bfc(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    int32_t i_v1 = i_a1; // 0x10bfc
    if (i_a4 == 0) {
        // 0x10bfe
        i_v1 = function_10ba0(i_a1, i_a2, i_a3, 0);
        int32_t i_v2; // 0x10bfc
        *(char *)i_v2 = 1;
    }
    // 0x10c06
    return i_v1;
}

// Address range: 0x10c08 - 0x10c0a
int32_t function_10c08(void) {
    // 0x10c08
    int32_t i_v1; // 0x10c08
    return i_v1;
}

// Address range: 0x10c0c - 0x10c7c
int32_t function_10c0c(int32_t i_a1) {
    int16_t **p_v1 = __ctype_b_loc(); // 0x10c14
    int32_t i_v2 = (int32_t)*p_v1;    // 0x10c1c
    uint32_t i_v3 = i_a1;             // 0x10c20
    while ((*(int16_t *)(2 * (int32_t) * (char *)i_v3 + i_v2) & 0x2000) != 0) {
        // 0x10c24
        i_v3++;
    }
    int32_t i_v4 = (int32_t)__rawmemchr((int32_t *)i_v3, 0); // 0x10c48
    if (i_v3 >= i_v4) {
        // 0x10c74
        return i_v3;
    }
    int32_t i_v5 = i_v4; // 0x10c54
    i_v5--;
    char *p_v6 = (char *)i_v5; // 0x10c54
    if ((*(int16_t *)(2 * (int32_t)*p_v6 + (int32_t)*p_v1) & 0x2000) != 0) {
        *p_v6 = 0;
    }
    while (i_v3 < i_v5) {
        // 0x10c54
        i_v5--;
        p_v6 = (char *)i_v5;
        if ((*(int16_t *)(2 * (int32_t)*p_v6 + (int32_t)*p_v1) & 0x2000) != 0) {
            *p_v6 = 0;
        }
    }
    // 0x10c74
    return i_v3;
}

// Address range: 0x10c7c - 0x10e10
int32_t display(int32_t i_a1) {
    // 0x10c7c
    if (i_a1 == 0) {
        // 0x10ce0
        return 0;
    }
    int32_t i_v1 = i_a1; // 0x10c88
    int32_t i_v2;        // 0x10c7c
    int32_t i_v3;        // 0x10c7c
    int32_t i_v4;        // 0x10c7c
    int32_t i_v5;        // 0x10c7c
    int32_t i_v6;        // 0x10c7c
    while (true) {
    lab_0x10ca8:
        // 0x10ca8
        i_v4 = i_v1;
        char *p_v7 = (char *)i_v4;      // 0x10cb0
        char *p_v8 = strchr(p_v7, 124); // 0x10cb0
        int32_t i_v9 = (int32_t)p_v8;   // 0x10cb0
        if (p_v8 == NULL) {
            // 0x10ce8
            i_v3 = i_v9;
            i_v6 = i_v9;
            if (*p_v7 == 0) {
                // break -> 0x10ce0
                break;
            }
            goto lab_0x10cf8;
        } else {
            int32_t i_v10 = i_v9 + 1; // 0x10cc0
            *p_v8 = 0;
            i_v2 = i_v9;
            i_v5 = i_v10;
            i_v6 = i_v10;
            if (*p_v7 == 0) {
                goto lab_0x10cd8;
            } else {
                goto lab_0x10cf8;
            }
        }
    }
lab_0x10ce0:
    // 0x10ce0
    return i_v3;
lab_0x10d1c:;
    // 0x10d1c
    int32_t i_v11; // 0x10c7c
    int32_t i_v12 = i_v11;
    char *p_v13;                     // 0x10c7c
    char *p_v14 = strchr(p_v13, 61); // 0x10d24
    char *p_v15;                     // 0x10c7c
    int32_t i_v16;                   // 0x10c7c
    int32_t i_v17;                   // 0x10c7c
    if (p_v14 == NULL) {
        if (i_v17 == 0) {
            // 0x10dfc
            printf("[%s%s] =>\n(\n", p_v13, (char *)&p_g1);
            // 0x10ddc
            printf("   [%d] => %s\n", i_v17, p_v13);
            i_v16 = i_v12;
            goto lab_0x10d90;
        } else {
            // 0x10ddc
            printf("   [%d] => %s\n", i_v17, p_v13);
            i_v16 = i_v12;
            goto lab_0x10d90;
        }
    } else {
        // 0x10d30
        *p_v14 = 0;
        int32_t i_v18 = (int32_t)p_v14 + 1; // 0x10d3c
        if (i_v17 == 0) {
            if (i_v18 == 0) {
                // 0x10dfc
                printf("[%s%s] =>\n(\n", p_v13, (char *)&p_g1);
                // 0x10ddc
                printf("   [%d] => %s\n", i_v17, p_v13);
                i_v16 = i_v12;
                goto lab_0x10d90;
            } else {
                int16_t **p_v19 = __ctype_b_loc(); // 0x10d4c
                char *p_v20 = (char *)i_v18;
                int16_t i_v21 = *(int16_t *)(2 * (int32_t)*p_v20 +
                                             (int32_t)*p_v19); // 0x10d64
                printf("[%s%s] =>\n(\n", p_v13,
                       (i_v21 & 2048) == 0 ? (char *)&p_g1 : p_v20);
                p_v15 = p_v20;
                goto lab_0x10d78;
            }
        } else {
            if (i_v18 == 0) {
                // 0x10ddc
                printf("   [%d] => %s\n", i_v17, p_v13);
                i_v16 = i_v12;
                goto lab_0x10d90;
            } else {
                // 0x10dd4
                p_v15 = (char *)i_v18;
                goto lab_0x10d78;
            }
        }
    }
lab_0x10d90:;
    int32_t i_v22 = i_v16;     // 0x10d98
    int32_t i_v23 = i_v17 + 1; // 0x10d98
    if (i_v16 == 0) {
        // break -> 0x10dc0
        goto lab_0x10dc0;
    }
    goto lab_0x10d9c;
lab_0x10d78:
    // 0x10d78
    printf("   [%s] => %s\n", p_v13, p_v15);
    i_v16 = i_v12;
    goto lab_0x10d90;
lab_0x10cf8:
    // 0x10cf8
    i_v22 = i_v4;
    i_v23 = 0;
    while (true) {
    lab_0x10d9c:
        // 0x10d9c
        i_v17 = i_v23;
        p_v13 = (char *)i_v22;
        char *p_v24 = strchr(p_v13, 44); // 0x10da4
        int32_t i_v25 = (int32_t)p_v24;  // 0x10da4
        if (p_v24 == NULL) {
            // 0x10db0
            i_v11 = i_v25;
            if (*p_v13 == 0) {
                // break -> 0x10dc0
                break;
            }
            goto lab_0x10d1c;
        } else {
            int32_t i_v26 = i_v25 + 1; // 0x10d04
            *p_v24 = 0;
            i_v11 = i_v26;
            i_v16 = i_v26;
            if (*p_v13 == 0) {
                goto lab_0x10d90;
            } else {
                goto lab_0x10d1c;
            }
        }
    }
lab_0x10dc0:
    // 0x10dc0
    i_v2 = puts(")");
    i_v5 = i_v6;
    goto lab_0x10cd8;
lab_0x10cd8:
    // 0x10cd8
    i_v1 = i_v5;
    i_v3 = i_v2;
    if (i_v1 == 0) {
        // break -> 0x10ce0
        goto lab_0x10ce0;
    }
    goto lab_0x10ca8;
}

// Address range: 0x10e10 - 0x11060
int32_t callapi(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    char *p_v1 = (char *)i_a2; // 0x10e28
    if (gethostbyname(p_v1) == NULL) {
        // 0x10f38
        printf("Couldn't get hostname: '%s'\n", p_v1);
        // 0x10f4c
        return 1;
    }
    int32_t i_v2 = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x10e40
    if (i_v2 == -1) {
        // 0x10f58
        printf("Socket initialisation failed: %s\n",
               strerror(*__errno_location()));
        return 1;
    }
    // 0x10e50
    __asm_rev16(i_a3);
    int32_t i_v3 = 2; // bp-48, 0x10e74
    if (connect(i_v2, (struct sockaddr *)&i_v3, 16) < 0) {
        // 0x10f84
        printf("Socket connect failed: %s\n", strerror(*__errno_location()));
        return 1;
    }
    // 0x10e98
    if (send(i_v2, (int32_t *)i_a1, strlen((char *)i_a1), 0) < 0) {
        // 0x11008
        printf("Send failed: %s\n", strerror(*__errno_location()));
        // 0x10ff4
        close(i_v2);
        return 1;
    }
    int32_t *p_v4 = malloc(0x10000); // 0x10ec0
    int32_t i_v5 = 0;                // 0x10ed0
    int32_t i_v6 = 0xffff;           // 0x10ed0
    int32_t *p_v7 = p_v4;            // 0x10ed0
    if (p_v4 == NULL) {
        // 0x11048
        printf("Err: OOM (%d)\n", 0x10000);
        // 0x10f4c
        return 1;
    }
    int32_t i_v8;   // 0x10e10
    int32_t i_v9;   // 0x10e10
    int32_t *p_v10; // 0x10e10
    int32_t i_v11;  // 0x10ed4
    while (true) {
        // 0x10ed4
        p_v10 = p_v7;
        i_v9 = (int32_t)p_v10;
        int32_t i_v12 = i_v5; // 0x10ef0
        i_v11 = i_v12 + i_v9;
        int32_t i_v13 =
            recv(i_v2, (int32_t *)i_v11, i_v6 - i_v12, 0); // 0x10ee8
        if (i_v13 < 0) {
            // break (via goto) -> 0x10fb0
            goto lab_0x10fb0;
        }
        // 0x10ef8
        i_v8 = 0;
        if (i_v13 == 0) {
            goto lab_0x10fd0;
        }
        // 0x10efc
        i_v12 += i_v13;
        while (i_v6 != i_v12) {
            // 0x10ed4
            i_v11 = i_v12 + i_v9;
            i_v13 = recv(i_v2, (int32_t *)i_v11, i_v6 - i_v12, 0);
            if (i_v13 < 0) {
                // break (via goto) -> 0x10fb0
                goto lab_0x10fb0;
            }
            // 0x10ef8
            i_v8 = 0;
            if (i_v13 == 0) {
                goto lab_0x10fd0;
            }
            // 0x10efc
            i_v12 += i_v13;
        }
        int32_t i_v14 = i_v6 + 0x10000; // 0x10f04
        p_v7 = realloc(p_v10, i_v14);
        i_v5 = i_v6;
        int32_t i_v15; // 0x10e10
        i_v6 += (p_v4 == NULL ? i_v15 : 0xffff);
        if (p_v7 == NULL) {
            // 0x10f20
            printf("Err: OOM (%d)\n", i_v14);
            return 1;
        }
    }
lab_0x10fb0:
    // 0x10fb0
    printf("Recv failed: %s\n", strerror(*__errno_location()));
    i_v8 = 1;
lab_0x10fd0:
    // 0x10fd0
    *(char *)i_v11 = 0;
    if (i_g5 != 0) {
        // 0x10fec
        puts((char *)p_v10);
        // 0x10ff4
        close(i_v2);
        return i_v8;
    }
    // 0x1102c
    printf("Reply was '%s'\n", p_v10);
    display(i_v9);
    // 0x10ff4
    close(i_v2);
    return i_v8;
}

// Address range: 0x11060 - 0x11094
int32_t __libc_csu_init(int32_t i_a1, int32_t i_a2, int32_t i_a3,
                        int32_t i_a4) {
    int32_t i_v1 = _init(i_a1, i_a2, i_a3, i_a4); // 0x11070
    return 0x21f12 - (int32_t)&i_g2 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x1109c - 0x1109e
int32_t __libc_csu_fini(void) {
    // 0x1109c
    int32_t i_v1; // 0x1109c
    return i_v1;
}

// Address range: 0x110a0 - 0x110a8
int32_t _fini(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x110a0
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 36
